# question_bank.py  – 100 questions for Singapore P4–P6 Chinese Oral Practice

QUESTIONS = [
    # ══════════════════════════════════════════════════════════
    # TOPIC: 家庭 FAMILY  (Q01-Q10)
    # ══════════════════════════════════════════════════════════
    {
        "id": "Q01", "level": "P4", "topic": "家庭",
        "emoji": "👨‍👩‍👧‍👦",
        "image_url": "https://images.unsplash.com/photo-1511895426328-dc8714191011?w=600",
        "image_caption": "一家人在一起 A happy family",
        "question_zh": "请描述这张图片，并说说你的家人是怎么相处的。",
        "question_en": "Describe this picture and talk about how your family members get along.",
        "vocab": ["家人", "关心", "帮助", "温暖", "一起"],
        "vocab_with_pinyin": [
            {"word": "家人", "pinyin": "jiārén", "meaning": "family members"},
            {"word": "关心", "pinyin": "guānxīn", "meaning": "to care for"},
            {"word": "温暖", "pinyin": "wēnnuǎn", "meaning": "warm/warmth"},
            {"word": "一起", "pinyin": "yīqǐ", "meaning": "together"},
        ],
        "model_answer": "图片里有一家人在一起。爸爸、妈妈和孩子们看起来很开心。家人之间要互相关心和帮助。我们家也经常一起吃饭、聊天，感情很好。",
        "followup_questions": [
            "你最喜欢和家人做什么活动？",
            "你怎么帮助家里做家务？",
        ],
        "scoring_hints": ["mentions family members", "describes relationship", "gives personal example"],
    },
    {
        "id": "Q02", "level": "P4", "topic": "家庭",
        "emoji": "🍽️",
        "image_url": "https://images.unsplash.com/photo-1529543544282-ea669407fca3?w=600",
        "image_caption": "全家一起吃饭",
        "question_zh": "图中的家人在做什么？你的家人会在什么时候聚在一起？",
        "question_en": "What is the family doing in the picture? When does your family gather together?",
        "vocab": ["聚餐", "欢聚", "节假日", "气氛", "热闹"],
        "vocab_with_pinyin": [
            {"word": "聚餐", "pinyin": "jùcān", "meaning": "to dine together"},
            {"word": "欢聚", "pinyin": "huānjù", "meaning": "happy reunion"},
            {"word": "热闹", "pinyin": "rènào", "meaning": "lively/bustling"},
        ],
        "model_answer": "图中的家人正在一起吃饭，大家谈笑风生，气氛很热闹。我的家人每逢节假日都会聚在一起，特别是农历新年，全家人一起包饺子、看电视，非常开心。",
        "followup_questions": ["你们家过节有什么特别的传统？"],
        "scoring_hints": ["describes picture", "mentions own family", "uses descriptive words"],
    },
    {
        "id": "Q03", "level": "P5", "topic": "家庭",
        "emoji": "👴👵",
        "image_url": "https://images.unsplash.com/photo-1574192864-0a36b64aef3b?w=600",
        "image_caption": "祖父母和孙子",
        "question_zh": "图中的祖父母正在做什么？说说你和祖父母之间的关系。",
        "question_en": "What are the grandparents doing in the picture? Talk about your relationship with your grandparents.",
        "vocab": ["祖父母", "尊重", "孝顺", "经验", "智慧"],
        "vocab_with_pinyin": [
            {"word": "尊重", "pinyin": "zūnzhòng", "meaning": "to respect"},
            {"word": "孝顺", "pinyin": "xiàoshùn", "meaning": "filial piety"},
            {"word": "智慧", "pinyin": "zhìhuì", "meaning": "wisdom"},
        ],
        "model_answer": "图中的祖父母正在教孙子做某件事，他们看起来很慈祥。我很尊重我的祖父母，他们有很多生活经验和智慧。我经常去探望他们，听他们讲故事。我们要孝顺长辈，这是中华文化的传统美德。",
        "followup_questions": ["你认为孝顺是什么意思？你是怎么孝顺父母的？"],
        "scoring_hints": ["describes image", "discusses filial piety", "cultural reference"],
    },
    {
        "id": "Q04", "level": "P6", "topic": "家庭",
        "emoji": "🏠",
        "image_url": "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=600",
        "image_caption": "父母教导孩子",
        "question_zh": "父母对孩子的成长有什么重要的影响？请举例说明。",
        "question_en": "What important influence do parents have on a child's growth? Give examples.",
        "vocab": ["榜样", "影响", "价值观", "培养", "成长"],
        "vocab_with_pinyin": [
            {"word": "榜样", "pinyin": "bǎngyàng", "meaning": "role model"},
            {"word": "价值观", "pinyin": "jiàzhíguān", "meaning": "values"},
            {"word": "培养", "pinyin": "péiyǎng", "meaning": "to nurture/cultivate"},
        ],
        "model_answer": "父母对孩子的成长影响非常深远。首先，父母是孩子的第一任老师，他们的言行举止会影响孩子的价值观。其次，父母给予孩子爱和安全感，让孩子能够自信地面对挑战。我的父母经常教导我要诚实守信，这对我影响很大。",
        "followup_questions": ["如果父母的做法不对，你会怎么处理？"],
        "scoring_hints": ["structured answer", "gives examples", "reflects on own experience"],
    },
    {
        "id": "Q05", "level": "P5", "topic": "家庭",
        "emoji": "👫",
        "image_url": "https://images.unsplash.com/photo-1516627145497-ae6968895b74?w=600",
        "image_caption": "兄弟姐妹在玩耍",
        "question_zh": "图中的孩子们在做什么？兄弟姐妹之间应该怎样相处？",
        "question_en": "What are the children doing? How should siblings get along?",
        "vocab": ["兄弟姐妹", "分享", "谦让", "争吵", "和好"],
        "vocab_with_pinyin": [
            {"word": "谦让", "pinyin": "qiānràng", "meaning": "to yield/be modest"},
            {"word": "分享", "pinyin": "fēnxiǎng", "meaning": "to share"},
        ],
        "model_answer": "图中的孩子们在一起玩耍，看起来很开心。兄弟姐妹之间要互相谦让和分享，有事情要好好商量，不要争吵。就算吵架了，也要很快和好，因为手足情是很珍贵的。",
        "followup_questions": ["你和兄弟姐妹吵架后是怎么和好的？"],
        "scoring_hints": ["describes image", "gives advice on sibling relationships", "personal reflection"],
    },
    {
        "id": "Q06", "level": "P4", "topic": "家庭",
        "emoji": "🎂",
        "image_url": "https://images.unsplash.com/photo-1464349095431-e9a21285b5f3?w=600",
        "image_caption": "家庭庆生",
        "question_zh": "这家人在庆祝什么？你们家是怎么庆祝生日的？",
        "question_en": "What is this family celebrating? How does your family celebrate birthdays?",
        "vocab": ["庆祝", "生日", "蜡烛", "许愿", "惊喜"],
        "vocab_with_pinyin": [
            {"word": "庆祝", "pinyin": "qìngzhù", "meaning": "to celebrate"},
            {"word": "许愿", "pinyin": "xǔyuàn", "meaning": "to make a wish"},
            {"word": "惊喜", "pinyin": "jīngxǐ", "meaning": "surprise"},
        ],
        "model_answer": "这家人在庆祝生日，大家围在一起，桌上有生日蛋糕，蜡烛正在燃烧，寿星正在许愿。我们家也会这样庆祝生日，还会一起去餐厅吃饭，互赠礼物，非常温馨。",
        "followup_questions": ["你最难忘的生日是哪一次？为什么？"],
        "scoring_hints": ["describes the picture", "relates to own experience"],
    },
    {
        "id": "Q07", "level": "P6", "topic": "家庭",
        "emoji": "📱",
        "image_url": "https://images.unsplash.com/photo-1611532736597-de2d4265fba3?w=600",
        "image_caption": "家人各自玩手机",
        "question_zh": "图中的情况说明了什么问题？你认为家人之间应该怎样保持良好的沟通？",
        "question_en": "What problem does this picture show? How should family members communicate well?",
        "vocab": ["沟通", "交流", "依赖", "影响", "疏远"],
        "vocab_with_pinyin": [
            {"word": "沟通", "pinyin": "gōutōng", "meaning": "to communicate"},
            {"word": "疏远", "pinyin": "shūyuǎn", "meaning": "to drift apart"},
        ],
        "model_answer": "图中的家人各自玩手机，彼此之间缺乏沟通，反映了现代社会中科技对家庭关系的负面影响。我认为家人之间应该定时放下手机，面对面交流，分享彼此的生活。我们家规定吃饭时不能玩手机，这个规矩很好。",
        "followup_questions": ["你认为手机对家庭关系有什么好处和坏处？"],
        "scoring_hints": ["identifies the problem", "gives suggestions", "balanced view"],
    },
    {
        "id": "Q08", "level": "P4", "topic": "家庭",
        "emoji": "🧹",
        "image_url": "https://images.unsplash.com/photo-1581578731548-c64695cc6952?w=600",
        "image_caption": "孩子帮忙做家务",
        "question_zh": "图中的孩子在做什么？你在家里有帮忙做家务吗？",
        "question_en": "What is the child in the picture doing? Do you help with housework at home?",
        "vocab": ["家务", "负责任", "清洗", "整理", "习惯"],
        "vocab_with_pinyin": [
            {"word": "负责任", "pinyin": "fùzérèn", "meaning": "responsible"},
            {"word": "整理", "pinyin": "zhěnglǐ", "meaning": "to tidy up"},
        ],
        "model_answer": "图中的孩子在帮忙做家务，这是很好的行为。我在家里也有帮忙做家务，比如扫地、洗碗和整理自己的房间。做家务能培养我们的责任感，也能让父母减轻负担。",
        "followup_questions": ["你觉得做家务对小孩子有什么好处？"],
        "scoring_hints": ["describes image", "mentions own experience", "explains benefits"],
    },
    {
        "id": "Q09", "level": "P5", "topic": "家庭",
        "emoji": "🏖️",
        "image_url": "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=600",
        "image_caption": "家庭旅行",
        "question_zh": "这家人在哪里？你最难忘的家庭旅行是什么？",
        "question_en": "Where is this family? What is your most memorable family trip?",
        "vocab": ["旅行", "风景", "难忘", "增进", "感情"],
        "vocab_with_pinyin": [
            {"word": "旅行", "pinyin": "lǚxíng", "meaning": "to travel"},
            {"word": "难忘", "pinyin": "nánwàng", "meaning": "unforgettable"},
            {"word": "增进", "pinyin": "zēngjìn", "meaning": "to enhance/improve"},
        ],
        "model_answer": "这家人在海边度假，蓝天白云，风景优美，他们看起来很享受。我最难忘的家庭旅行是去日本，那里的樱花非常美丽。旅行能增进家人之间的感情，让我们留下美好的回忆。",
        "followup_questions": ["家庭旅行对你们家来说有什么意义？"],
        "scoring_hints": ["describes image", "shares personal experience", "reflects on meaning"],
    },
    {
        "id": "Q10", "level": "P6", "topic": "家庭",
        "emoji": "👨‍👩‍👦",
        "image_url": "https://images.unsplash.com/photo-1599059813005-11265ba4b4ce?w=600",
        "image_caption": "单亲家庭",
        "question_zh": "不同的家庭有不同的结构。你认为什么是幸福的家庭？",
        "question_en": "Different families have different structures. What do you think makes a happy family?",
        "vocab": ["幸福", "理解", "支持", "结构", "相互"],
        "vocab_with_pinyin": [
            {"word": "幸福", "pinyin": "xìngfú", "meaning": "happy/happiness"},
            {"word": "理解", "pinyin": "lǐjiě", "meaning": "to understand"},
        ],
        "model_answer": "幸福的家庭不在于家庭结构，而在于家人之间的爱与理解。无论是大家庭还是小家庭，只要家人互相支持、坦诚沟通，就能建立幸福的家。我认为幸福的家庭需要爱、尊重和包容。",
        "followup_questions": ["你认为金钱能买到家庭幸福吗？为什么？"],
        "scoring_hints": ["defines happiness", "avoids stereotypes", "gives personal view"],
    },

    # ══════════════════════════════════════════════════════════
    # TOPIC: 学校 SCHOOL  (Q11-Q20)
    # ══════════════════════════════════════════════════════════
    {
        "id": "Q11", "level": "P4", "topic": "学校",
        "emoji": "🏫",
        "image_url": "https://images.unsplash.com/photo-1580582932707-520aed937b7b?w=600",
        "image_caption": "学生在课室上课",
        "question_zh": "图中的同学们在做什么？你最喜欢学校的哪一节课？为什么？",
        "question_en": "What are the students doing? What is your favourite subject? Why?",
        "vocab": ["上课", "认真", "专心", "学习", "兴趣"],
        "vocab_with_pinyin": [
            {"word": "认真", "pinyin": "rènzhēn", "meaning": "serious/diligent"},
            {"word": "专心", "pinyin": "zhuānxīn", "meaning": "focused/attentive"},
        ],
        "model_answer": "图中的同学们正在认真上课，老师在黑板前讲解，同学们专心听讲。我最喜欢的是华文课，因为我喜欢学习成语故事和写作文。上课专心听讲能让我们学到更多知识。",
        "followup_questions": ["你觉得怎样才能在课堂上学得更好？"],
        "scoring_hints": ["describes image", "states favourite subject", "gives reason"],
    },
    {
        "id": "Q12", "level": "P4", "topic": "学校",
        "emoji": "🤝",
        "image_url": "https://images.unsplash.com/photo-1509062522246-3755977927d7?w=600",
        "image_caption": "同学们一起合作",
        "question_zh": "图中的同学们在做什么？你认为合作学习有什么好处？",
        "question_en": "What are the classmates doing? What are the benefits of cooperative learning?",
        "vocab": ["合作", "团队", "互补", "分工", "共同"],
        "vocab_with_pinyin": [
            {"word": "合作", "pinyin": "hézuò", "meaning": "to cooperate"},
            {"word": "分工", "pinyin": "fēngōng", "meaning": "division of labour"},
        ],
        "model_answer": "图中的同学们正在分组合作学习，每个人都在贡献自己的意见。合作学习有很多好处：可以互相学习、取长补短，还能培养团队精神。我喜欢和同学一起做项目，因为大家的想法合在一起会更完整。",
        "followup_questions": ["合作时遇到意见不同怎么办？"],
        "scoring_hints": ["describes image", "lists benefits", "gives personal example"],
    },
    {
        "id": "Q13", "level": "P5", "topic": "学校",
        "emoji": "🎒",
        "image_url": "https://images.unsplash.com/photo-1503676260728-1c00da094a0b?w=600",
        "image_caption": "学校运动会",
        "question_zh": "图中的同学们在参加什么活动？课外活动对学生有什么帮助？",
        "question_en": "What activity are the students participating in? How do CCAs help students?",
        "vocab": ["课外活动", "全面发展", "体魄", "才艺", "精神"],
        "vocab_with_pinyin": [
            {"word": "全面发展", "pinyin": "quánmiàn fāzhǎn", "meaning": "holistic development"},
            {"word": "体魄", "pinyin": "tǐpò", "meaning": "physique/body"},
        ],
        "model_answer": "图中的同学们正在参加学校运动会，大家精神饱满，奋力竞争。课外活动对学生帮助很大，不仅能锻炼身体，还能培养领导能力和团队精神。我参加了篮球队，学到了坚持不懈的精神。",
        "followup_questions": ["你参加了什么课外活动？你从中学到了什么？"],
        "scoring_hints": ["describes image", "gives benefits of CCAs", "personal CCA experience"],
    },
    {
        "id": "Q14", "level": "P5", "topic": "学校",
        "emoji": "📚",
        "image_url": "https://images.unsplash.com/photo-1456513080510-7bf3a84b82f8?w=600",
        "image_caption": "图书馆阅读",
        "question_zh": "图中的地方是哪里？你喜欢去图书馆吗？为什么？",
        "question_en": "What place is shown? Do you like going to the library? Why?",
        "vocab": ["图书馆", "阅读", "知识", "安静", "书籍"],
        "vocab_with_pinyin": [
            {"word": "图书馆", "pinyin": "túshūguǎn", "meaning": "library"},
            {"word": "阅读", "pinyin": "yuèdú", "meaning": "to read"},
        ],
        "model_answer": "图中的地方是图书馆，有许多书架和安静的阅读区。我很喜欢去图书馆，因为那里有很多有趣的书，可以增长知识。图书馆安静的环境让我能专心阅读。我每个星期都会去借几本书回家看。",
        "followup_questions": ["你最近读了什么书？内容是什么？"],
        "scoring_hints": ["identifies location", "expresses opinion", "gives reason"],
    },
    {
        "id": "Q15", "level": "P6", "topic": "学校",
        "emoji": "👨‍🏫",
        "image_url": "https://images.unsplash.com/photo-1524178232363-1fb2b075b655?w=600",
        "image_caption": "老师在指导学生",
        "question_zh": "图中的老师在做什么？老师对你的学习和成长有什么影响？",
        "question_en": "What is the teacher doing? What influence has a teacher had on you?",
        "vocab": ["指导", "启发", "耐心", "榜样", "感激"],
        "vocab_with_pinyin": [
            {"word": "启发", "pinyin": "qǐfā", "meaning": "to inspire/enlighten"},
            {"word": "感激", "pinyin": "gǎnjī", "meaning": "grateful"},
        ],
        "model_answer": "图中的老师正在耐心地指导学生，帮助他们解决学习上的困难。老师对我的影响非常深远。我的华文老师不仅教会我语言技巧，还经常用故事启发我思考人生道理。我非常感激我的老师们，没有他们就没有今天的我。",
        "followup_questions": ["如果你将来当老师，你会怎么教学生？"],
        "scoring_hints": ["describes image", "gives specific teacher influence", "shows gratitude"],
    },
    {
        "id": "Q16", "level": "P4", "topic": "学校",
        "emoji": "🍱",
        "image_url": "https://images.unsplash.com/photo-1567521464027-f127ff144326?w=600",
        "image_caption": "学校食堂",
        "question_zh": "图中是学校的哪个地方？你通常在学校吃什么？",
        "question_en": "What school area is this? What do you usually eat at school?",
        "vocab": ["食堂", "营养", "排队", "健康", "小贩"],
        "vocab_with_pinyin": [
            {"word": "食堂", "pinyin": "shítáng", "meaning": "canteen"},
            {"word": "营养", "pinyin": "yíngyǎng", "meaning": "nutrition"},
        ],
        "model_answer": "图中是学校的食堂，有很多摊位出售各种食物。我通常在学校食堂买鸡饭或炒面。食堂的食物种类很多，我们要选择营养均衡的食物，这样才能有足够的精力上课。",
        "followup_questions": ["你认为学校食堂的食物健康吗？为什么？"],
        "scoring_hints": ["identifies the canteen", "describes what they eat", "mentions nutrition"],
    },
    {
        "id": "Q17", "level": "P5", "topic": "学校",
        "emoji": "🤕",
        "image_url": "https://images.unsplash.com/photo-1588776814546-1ffedbc2c641?w=600",
        "image_caption": "同学被欺负",
        "question_zh": "如果你看到同学被欺负，你会怎么做？",
        "question_en": "If you see a classmate being bullied, what would you do?",
        "vocab": ["霸凌", "勇气", "告诉", "老师", "保护"],
        "vocab_with_pinyin": [
            {"word": "霸凌", "pinyin": "bàlíng", "meaning": "bullying"},
            {"word": "勇气", "pinyin": "yǒngqì", "meaning": "courage"},
        ],
        "model_answer": "如果我看到同学被欺负，我会先保持冷静，不要直接冲突。我会告诉老师或其他大人，因为成年人有能力更好地处理这件事。我也会安慰被欺负的同学，让他知道他不是一个人。我们每个人都有责任维护一个安全的校园环境。",
        "followup_questions": ["你认为为什么有些同学会去欺负别人？"],
        "scoring_hints": ["gives clear action plan", "mentions reporting to adults", "shows empathy"],
    },
    {
        "id": "Q18", "level": "P6", "topic": "学校",
        "emoji": "🏆",
        "image_url": "https://images.unsplash.com/photo-1540575467063-178a50c2df87?w=600",
        "image_caption": "颁奖典礼",
        "question_zh": "图中正在举行什么活动？得奖对你有什么意义？",
        "question_en": "What event is happening? What does winning an award mean to you?",
        "vocab": ["颁奖", "努力", "成就", "鼓励", "坚持"],
        "vocab_with_pinyin": [
            {"word": "颁奖", "pinyin": "bānjiǎng", "meaning": "award ceremony"},
            {"word": "成就", "pinyin": "chéngjiù", "meaning": "achievement"},
        ],
        "model_answer": "图中正在举行颁奖典礼，获奖的同学站在台上，看起来非常自豪。对我来说，得奖不是最重要的，最重要的是努力的过程。每一次参加比赛，都让我学到新的知识和技能。得奖固然高兴，但没有得奖也不应该气馁，继续努力才是正确的态度。",
        "followup_questions": ["如果你非常努力却没有得奖，你会怎么面对？"],
        "scoring_hints": ["describes event", "balanced view on winning", "mature reflection"],
    },
    {
        "id": "Q19", "level": "P4", "topic": "学校",
        "emoji": "🎨",
        "image_url": "https://images.unsplash.com/photo-1513364776144-60967b0f800f?w=600",
        "image_caption": "美术课",
        "question_zh": "图中的同学们在上什么课？你喜欢做什么课外活动？",
        "question_en": "What lesson are the students having? What activities do you enjoy?",
        "vocab": ["美术", "创意", "作品", "色彩", "才华"],
        "vocab_with_pinyin": [
            {"word": "创意", "pinyin": "chuàngyì", "meaning": "creativity"},
            {"word": "色彩", "pinyin": "sècǎi", "meaning": "colours"},
        ],
        "model_answer": "图中的同学们正在上美术课，大家都在专心地画画，作品五彩缤纷。我喜欢上美术课，因为可以自由发挥创意。课外活动方面，我参加了学校的绘画小组，每周都有机会画画，我觉得很有趣。",
        "followup_questions": ["你认为艺术教育对学生重要吗？为什么？"],
        "scoring_hints": ["identifies art class", "mentions own hobbies", "gives reason"],
    },
    {
        "id": "Q20", "level": "P6", "topic": "学校",
        "emoji": "💻",
        "image_url": "https://images.unsplash.com/photo-1516321318423-f06f85e504b3?w=600",
        "image_caption": "电脑课",
        "question_zh": "科技在学习中扮演着什么角色？有什么好处和坏处？",
        "question_en": "What role does technology play in learning? What are the pros and cons?",
        "vocab": ["科技", "利弊", "效率", "分散", "注意力"],
        "vocab_with_pinyin": [
            {"word": "利弊", "pinyin": "lìbì", "meaning": "pros and cons"},
            {"word": "效率", "pinyin": "xiàolǜ", "meaning": "efficiency"},
        ],
        "model_answer": "科技在现代学习中扮演着越来越重要的角色。好处方面，电脑和网络让我们能够轻松获取大量知识，提高学习效率。坏处方面，学生可能会沉迷于游戏或社交媒体，分散学习的注意力。因此，我们要合理使用科技，把它变成学习的工具，而不是娱乐的工具。",
        "followup_questions": ["你认为学校应该允许学生带手机上学吗？"],
        "scoring_hints": ["balanced discussion", "pros and cons", "gives conclusion"],
    },

    # ══════════════════════════════════════════════════════════
    # TOPIC: 节日 FESTIVALS  (Q21-Q30)
    # ══════════════════════════════════════════════════════════
    {
        "id": "Q21", "level": "P4", "topic": "节日",
        "emoji": "🧧",
        "image_url": "https://images.unsplash.com/photo-1611174275727-3f6e0e3e3e9e?w=600",
        "image_caption": "农历新年装饰",
        "question_zh": "图中是什么节日的装饰？你最喜欢农历新年的哪个传统？",
        "question_en": "What festival decorations are shown? What CNY tradition do you love most?",
        "vocab": ["农历新年", "红包", "团圆饭", "装饰", "传统"],
        "vocab_with_pinyin": [
            {"word": "红包", "pinyin": "hóngbāo", "meaning": "red packet"},
            {"word": "团圆饭", "pinyin": "tuányuán fàn", "meaning": "reunion dinner"},
        ],
        "model_answer": "图中是农历新年的装饰，有红灯笼、春联和各种喜庆的摆设。我最喜欢农历新年的团圆饭，全家人聚在一起，桌上摆满了各种美食，气氛非常热闹温馨。收红包也很开心，但更重要的是能与亲戚们见面聊天。",
        "followup_questions": ["农历新年有什么风俗让你印象最深刻？"],
        "scoring_hints": ["identifies festival", "describes favourite tradition", "explains why"],
    },
    {
        "id": "Q22", "level": "P4", "topic": "节日",
        "emoji": "🏮",
        "image_url": "https://images.unsplash.com/photo-1546842931-886c185b4c8c?w=600",
        "image_caption": "中秋节提灯笼",
        "question_zh": "图中的孩子在做什么？说说中秋节有什么特别的习俗。",
        "question_en": "What are the children doing? Talk about Mid-Autumn Festival customs.",
        "vocab": ["中秋节", "灯笼", "月饼", "赏月", "习俗"],
        "vocab_with_pinyin": [
            {"word": "赏月", "pinyin": "shǎngyuè", "meaning": "to admire the moon"},
            {"word": "习俗", "pinyin": "xísú", "meaning": "customs/traditions"},
        ],
        "model_answer": "图中的孩子们在提着灯笼庆祝中秋节，五颜六色的灯笼照亮了夜晚，看起来非常美丽。中秋节有很多特别的习俗，比如吃月饼、赏月和提灯笼。我最喜欢和家人一起坐在户外赏月，一边吃月饼一边聊天。",
        "followup_questions": ["中秋节和农历新年有什么不同？"],
        "scoring_hints": ["describes image", "lists customs", "personal connection"],
    },
    {
        "id": "Q23", "level": "P5", "topic": "节日",
        "emoji": "🪔",
        "image_url": "https://images.unsplash.com/photo-1605117882932-f9e32b03fea9?w=600",
        "image_caption": "屠妖节油灯",
        "question_zh": "这是什么节日？新加坡是一个多元种族社会，节日对促进种族和谐有什么作用？",
        "question_en": "What festival is this? How do festivals promote racial harmony in Singapore?",
        "vocab": ["屠妖节", "种族", "和谐", "庆祝", "了解"],
        "vocab_with_pinyin": [
            {"word": "种族和谐", "pinyin": "zhǒngzú héxié", "meaning": "racial harmony"},
            {"word": "屠妖节", "pinyin": "túyāo jié", "meaning": "Deepavali"},
        ],
        "model_answer": "这是屠妖节（Deepavali），是印度族同胞的重要节日，象征光明战胜黑暗。新加坡是一个多元种族的国家，各族人民共同庆祝彼此的节日，这能增进相互了解和尊重。我曾受邀到印度朋友家里参加屠妖节的庆祝，感受到不同文化的美好。",
        "followup_questions": ["你参加过其他种族的节日庆典吗？有什么感受？"],
        "scoring_hints": ["identifies festival", "discusses racial harmony", "personal experience"],
    },
    {
        "id": "Q24", "level": "P5", "topic": "节日",
        "emoji": "☪️",
        "image_url": "https://images.unsplash.com/photo-1610878180933-123728745d22?w=600",
        "image_caption": "开斋节庆祝",
        "question_zh": "图中是什么节日？你了解这个节日的意义吗？",
        "question_en": "What festival is shown? Do you know its significance?",
        "vocab": ["开斋节", "斋戒", "意义", "庆祝", "友族"],
        "vocab_with_pinyin": [
            {"word": "开斋节", "pinyin": "kāizhāi jié", "meaning": "Hari Raya/Eid"},
            {"word": "斋戒", "pinyin": "zhāijiè", "meaning": "fasting"},
        ],
        "model_answer": "图中是开斋节（Hari Raya Puasa）的庆祝活动，马来族同胞在完成一个月的斋戒后庆祝这个节日。开斋节代表感恩、宽恕和新的开始。在新加坡，各族人民都会互相拜访庆祝，体现了我们社会的种族和谐精神。",
        "followup_questions": ["你觉得了解其他种族的节日为什么重要？"],
        "scoring_hints": ["identifies Hari Raya", "explains significance", "racial harmony angle"],
    },
    {
        "id": "Q25", "level": "P4", "topic": "节日",
        "emoji": "🐉",
        "image_url": "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=600",
        "image_caption": "端午节赛龙舟",
        "question_zh": "图中的人在参加什么活动？端午节有什么特别的食物和活动？",
        "question_en": "What activity is shown? What special foods and activities are there for Dragon Boat Festival?",
        "vocab": ["端午节", "粽子", "赛龙舟", "屈原", "传说"],
        "vocab_with_pinyin": [
            {"word": "粽子", "pinyin": "zòngzi", "meaning": "rice dumpling"},
            {"word": "赛龙舟", "pinyin": "sài lóngzhōu", "meaning": "dragon boat racing"},
        ],
        "model_answer": "图中的人们在参加端午节的赛龙舟比赛，大家齐心协力，划船声响亮，气氛非常热烈。端午节的特别食物是粽子，里面有糯米、肉和蛋黄，非常美味。端午节的由来和古代爱国诗人屈原有关，充满了历史意义。",
        "followup_questions": ["你知道端午节的历史来源吗？"],
        "scoring_hints": ["describes dragon boat racing", "mentions zongzi", "knows the legend"],
    },
    {
        "id": "Q26", "level": "P6", "topic": "节日",
        "emoji": "🎊",
        "image_url": "https://images.unsplash.com/photo-1467810563316-b5476525c0f9?w=600",
        "image_caption": "新年烟火",
        "question_zh": "图中是什么场景？现代人庆祝节日的方式和以前有什么不同？",
        "question_en": "What is shown? How has the way people celebrate festivals changed?",
        "vocab": ["烟火", "传统", "现代", "变化", "保留"],
        "vocab_with_pinyin": [
            {"word": "烟火", "pinyin": "yānhuǒ", "meaning": "fireworks"},
            {"word": "传统", "pinyin": "chuántǒng", "meaning": "tradition"},
        ],
        "model_answer": "图中是烟火表演，人们在迎接新年的到来。现代人庆祝节日的方式确实有所改变。以前的人注重家庭聚会和传统习俗，而现在很多人会在社交媒体上分享节日照片，或者去商场购物。我认为我们应该在享受现代庆祝方式的同时，也保留传统习俗，因为这是我们的文化根源。",
        "followup_questions": ["你认为传统节日的习俗会消失吗？为什么？"],
        "scoring_hints": ["describes image", "compares old vs new", "gives opinion on preservation"],
    },
    {
        "id": "Q27", "level": "P4", "topic": "节日",
        "emoji": "🎁",
        "image_url": "https://images.unsplash.com/photo-1512909006721-3d6018887383?w=600",
        "image_caption": "圣诞节装饰",
        "question_zh": "图中是什么节日的布置？你喜欢圣诞节吗？为什么？",
        "question_en": "What festive decorations are shown? Do you like Christmas? Why?",
        "vocab": ["圣诞节", "礼物", "装饰", "祝福", "温馨"],
        "vocab_with_pinyin": [
            {"word": "圣诞节", "pinyin": "shèngdàn jié", "meaning": "Christmas"},
            {"word": "祝福", "pinyin": "zhùfú", "meaning": "blessings/wishes"},
        ],
        "model_answer": "图中是圣诞节的装饰，有圣诞树、彩灯和礼物，看起来非常温馨。我喜欢圣诞节，因为这个时候商场和街道都装饰得很漂亮，气氛很欢乐。在新加坡，无论是哪个种族，大家都会一起庆祝圣诞节，体现了我们社会的包容性。",
        "followup_questions": ["你认为圣诞节是新加坡人的节日吗？为什么？"],
        "scoring_hints": ["describes decorations", "expresses opinion", "Singapore multicultural angle"],
    },
    {
        "id": "Q28", "level": "P5", "topic": "节日",
        "emoji": "🌺",
        "image_url": "https://images.unsplash.com/photo-1528360983277-13d401cdc186?w=600",
        "image_caption": "七月半祭祖",
        "question_zh": "图中的人在做什么？你了解华人的祭祖文化吗？",
        "question_en": "What are people doing? What do you know about Chinese ancestral worship culture?",
        "vocab": ["祭祖", "传承", "孝道", "纪念", "文化"],
        "vocab_with_pinyin": [
            {"word": "祭祖", "pinyin": "jìzǔ", "meaning": "ancestral worship"},
            {"word": "传承", "pinyin": "chuánchéng", "meaning": "to pass down/inherit"},
        ],
        "model_answer": "图中的人们在祭祖，献上食物和香烛，表达对祖先的思念和尊重。祭祖文化是华人传统文化的重要部分，体现了我们对祖先的感恩和孝道精神。通过祭祖，我们也传承了家族的历史和文化，让后代不忘根源。",
        "followup_questions": ["你认为年轻一代还应该保留祭祖的传统吗？"],
        "scoring_hints": ["describes activity", "explains cultural significance", "gives opinion on tradition"],
    },
    {
        "id": "Q29", "level": "P4", "topic": "节日",
        "emoji": "🍡",
        "image_url": "https://images.unsplash.com/photo-1563245372-f21724e3856d?w=600",
        "image_caption": "汤圆",
        "question_zh": "图中的食物是什么？它和哪个节日有关？",
        "question_en": "What food is shown? Which festival is it associated with?",
        "vocab": ["汤圆", "冬至", "团圆", "甜蜜", "象征"],
        "vocab_with_pinyin": [
            {"word": "汤圆", "pinyin": "tāngyuán", "meaning": "glutinous rice balls"},
            {"word": "冬至", "pinyin": "dōngzhì", "meaning": "Winter Solstice"},
            {"word": "象征", "pinyin": "xiàngzhēng", "meaning": "to symbolise"},
        ],
        "model_answer": "图中的食物是汤圆，圆形的汤圆象征着团团圆圆。汤圆和冬至节有关，每逢冬至，华人家庭都会一起搓汤圆、吃汤圆，表示家庭团聚和甜甜蜜蜜。我很喜欢冬至，因为可以和家人一起搓汤圆，非常有趣。",
        "followup_questions": ["你喜欢哪种口味的汤圆？为什么冬至要吃汤圆？"],
        "scoring_hints": ["identifies tangyuan", "connects to dongzhi", "explains symbolism"],
    },
    {
        "id": "Q30", "level": "P6", "topic": "节日",
        "emoji": "🏛️",
        "image_url": "https://images.unsplash.com/photo-1562602833-0f4ab2fc46e5?w=600",
        "image_caption": "国庆日游行",
        "question_zh": "图中是什么活动？新加坡国庆日对你来说有什么意义？",
        "question_en": "What is happening? What does Singapore National Day mean to you?",
        "vocab": ["国庆日", "爱国", "身份", "多元", "骄傲"],
        "vocab_with_pinyin": [
            {"word": "国庆日", "pinyin": "guóqìng rì", "meaning": "National Day"},
            {"word": "爱国", "pinyin": "àiguó", "meaning": "patriotic"},
        ],
        "model_answer": "图中是新加坡国庆日的庆典活动，有精彩的游行表演，展示了新加坡各族人民的文化和成就。国庆日对我来说意义深远，它让我想起新加坡建国的艰辛历程和先辈们的努力。身为新加坡人，我感到非常骄傲，因为我们在一个多元种族的社会里和平共处，共同建设美好家园。",
        "followup_questions": ["作为新加坡年轻人，你认为应该怎样为国家作贡献？"],
        "scoring_hints": ["describes NDP", "expresses patriotism", "reflects on Singapore identity"],
    },

    # ══════════════════════════════════════════════════════════
    # TOPIC: 环境 ENVIRONMENT  (Q31-Q40)
    # ══════════════════════════════════════════════════════════
    {
        "id": "Q31", "level": "P4", "topic": "环境",
        "emoji": "♻️",
        "image_url": "https://images.unsplash.com/photo-1532996122724-e3c354a0b15b?w=600",
        "image_caption": "垃圾分类回收",
        "question_zh": "图中的人在做什么？为什么我们要回收垃圾？",
        "question_en": "What is the person doing? Why should we recycle?",
        "vocab": ["回收", "环保", "减少", "废物", "资源"],
        "vocab_with_pinyin": [
            {"word": "回收", "pinyin": "huíshōu", "meaning": "to recycle"},
            {"word": "环保", "pinyin": "huánbǎo", "meaning": "environmentally friendly"},
        ],
        "model_answer": "图中的人正在把垃圾分类放入不同的回收桶，这是非常好的环保行为。我们要回收垃圾，因为这样可以减少垃圾量，节约资源，保护环境。在我们学校，每个课室都有回收箱，我每天都会把废纸放进去。",
        "followup_questions": ["你在家里和学校是怎么做到环保的？"],
        "scoring_hints": ["describes recycling", "gives reasons", "personal action"],
    },
    {
        "id": "Q32", "level": "P5", "topic": "环境",
        "emoji": "🌊",
        "image_url": "https://images.unsplash.com/photo-1483683804023-6ccdb62f86ef?w=600",
        "image_caption": "海滩垃圾污染",
        "question_zh": "图中的海滩有什么问题？我们应该怎样保护海洋环境？",
        "question_en": "What problem is shown at the beach? How can we protect the ocean?",
        "vocab": ["污染", "海洋", "保护", "生态", "垃圾"],
        "vocab_with_pinyin": [
            {"word": "污染", "pinyin": "wūrǎn", "meaning": "pollution"},
            {"word": "生态", "pinyin": "shēngtài", "meaning": "ecology/ecosystem"},
        ],
        "model_answer": "图中的海滩布满了垃圾，这是严重的环境污染问题。这些垃圾会伤害海洋生物，破坏生态环境。我们应该减少使用一次性塑料制品，不要乱丢垃圾，还可以参加海滩清洁活动。保护海洋是每个人的责任，我们要从自己做起。",
        "followup_questions": ["塑料污染对海洋生物有什么影响？"],
        "scoring_hints": ["identifies problem", "gives solutions", "sense of personal responsibility"],
    },
    {
        "id": "Q33", "level": "P6", "topic": "环境",
        "emoji": "🌡️",
        "image_url": "https://images.unsplash.com/photo-1508193638397-1c4234db14d8?w=600",
        "image_caption": "全球暖化影响",
        "question_zh": "全球暖化对地球有什么影响？我们能做什么？",
        "question_en": "What are the effects of global warming? What can we do?",
        "vocab": ["全球暖化", "气候", "碳排放", "可再生", "能源"],
        "vocab_with_pinyin": [
            {"word": "全球暖化", "pinyin": "quánqiú nuǎnhuà", "meaning": "global warming"},
            {"word": "碳排放", "pinyin": "tàn páifàng", "meaning": "carbon emissions"},
        ],
        "model_answer": "全球暖化导致地球温度升高，冰川融化，海平面上升，极端天气事件频繁发生，对地球上的生命造成很大威胁。为了解决这个问题，我们可以节约用电，减少驾车，改用公共交通，以及支持可再生能源的发展。政府、企业和个人都需要共同努力才能解决这个全球性问题。",
        "followup_questions": ["新加坡有哪些应对气候变化的措施？"],
        "scoring_hints": ["explains effects", "gives solutions at different levels", "local context"],
    },
    {
        "id": "Q34", "level": "P4", "topic": "环境",
        "emoji": "🌳",
        "image_url": "https://images.unsplash.com/photo-1448375240586-882707db888b?w=600",
        "image_caption": "种树活动",
        "question_zh": "图中的人们在做什么？种树对环境有什么好处？",
        "question_en": "What are the people doing? What are the benefits of planting trees?",
        "vocab": ["种树", "绿化", "氧气", "遮荫", "美化"],
        "vocab_with_pinyin": [
            {"word": "绿化", "pinyin": "lǜhuà", "meaning": "greening/afforestation"},
            {"word": "遮荫", "pinyin": "zhēyīn", "meaning": "to provide shade"},
        ],
        "model_answer": "图中的人们正在种树，这是一项非常有意义的环保活动。种树的好处有很多：树木能吸收二氧化碳，释放氧气，帮助净化空气；树木还能提供遮荫，让城市更凉爽；同时树木也能美化环境，让城市变得更绿色。新加坡是一个花园城市，种树是我们一直以来的传统。",
        "followup_questions": ["新加坡为什么被称为'花园城市'？"],
        "scoring_hints": ["describes tree planting", "multiple benefits", "Singapore context"],
    },
    {
        "id": "Q35", "level": "P5", "topic": "环境",
        "emoji": "💧",
        "image_url": "https://images.unsplash.com/photo-1594456615503-13e5e1e4f15b?w=600",
        "image_caption": "节约用水",
        "question_zh": "图中展示了什么信息？在新加坡，节约用水为什么特别重要？",
        "question_en": "What message does the image convey? Why is water conservation especially important in Singapore?",
        "vocab": ["节约", "水资源", "珍贵", "依赖", "进口"],
        "vocab_with_pinyin": [
            {"word": "水资源", "pinyin": "shuǐ zīyuán", "meaning": "water resources"},
            {"word": "珍贵", "pinyin": "zhēnguì", "meaning": "precious/valuable"},
        ],
        "model_answer": "图中提醒我们要节约用水。在新加坡，节约用水特别重要，因为我们是一个面积小、自然资源有限的岛国，部分水源需要依赖进口。政府推行了NEWater等创新水务科技，但我们每个人也要做好节约用水的本分，比如关紧水龙头、缩短淋浴时间。",
        "followup_questions": ["你知道新加坡的'四个国家水龙头'是什么吗？"],
        "scoring_hints": ["discusses water scarcity", "Singapore specific context", "personal actions"],
    },
    {
        "id": "Q36", "level": "P4", "topic": "环境",
        "emoji": "🐘",
        "image_url": "https://images.unsplash.com/photo-1564760055775-d63b17a55c44?w=600",
        "image_caption": "濒临绝种的动物",
        "question_zh": "图中的动物是什么？它为什么面临绝种的危险？",
        "question_en": "What animal is this? Why is it endangered?",
        "vocab": ["濒临绝种", "栖息地", "猎杀", "保护", "野生动物"],
        "vocab_with_pinyin": [
            {"word": "濒临绝种", "pinyin": "bīnlín juézhǒng", "meaning": "endangered"},
            {"word": "栖息地", "pinyin": "qīxīdì", "meaning": "habitat"},
        ],
        "model_answer": "图中的动物是大象，它是一种濒临绝种的动物。大象面临绝种的危险，主要因为人类大量破坏森林，使大象失去栖息地；还有不法分子为了象牙而猎杀大象。我们应该保护野生动物，因为它们是地球生态系统的重要一部分。",
        "followup_questions": ["你认为我们应该怎样保护濒临绝种的动物？"],
        "scoring_hints": ["identifies elephant", "gives reasons for endangerment", "suggests protection"],
    },
    {
        "id": "Q37", "level": "P5", "topic": "环境",
        "emoji": "🌞",
        "image_url": "https://images.unsplash.com/photo-1509391366360-2e959784a276?w=600",
        "image_caption": "太阳能板",
        "question_zh": "图中是什么设备？使用可再生能源有什么好处？",
        "question_en": "What equipment is shown? What are the benefits of renewable energy?",
        "vocab": ["太阳能", "可再生", "清洁", "环保", "持续"],
        "vocab_with_pinyin": [
            {"word": "太阳能", "pinyin": "tàiyáng néng", "meaning": "solar energy"},
            {"word": "可再生能源", "pinyin": "kě zàishēng néngyuán", "meaning": "renewable energy"},
        ],
        "model_answer": "图中是太阳能板，用来将太阳光转化为电能。使用可再生能源好处很多：太阳能是取之不尽的自然资源，不会排放污染物，对环境友好。新加坡政府也在推广使用太阳能，很多组屋屋顶都安装了太阳能板。我认为大力发展可再生能源是解决能源问题和环境问题的重要途径。",
        "followup_questions": ["新加坡在可再生能源方面面临什么挑战？"],
        "scoring_hints": ["identifies solar panels", "lists benefits", "Singapore context"],
    },
    {
        "id": "Q38", "level": "P6", "topic": "环境",
        "emoji": "🥤",
        "image_url": "https://images.unsplash.com/photo-1542601906990-b4d3fb778b09?w=600",
        "image_caption": "一次性塑料",
        "question_zh": "图中的物品造成什么环境问题？我们应该怎样减少使用一次性塑料？",
        "question_en": "What environmental problem do these items cause? How can we reduce single-use plastics?",
        "vocab": ["一次性", "塑料", "替代品", "自带", "习惯"],
        "vocab_with_pinyin": [
            {"word": "一次性", "pinyin": "yīcìxìng", "meaning": "single-use/disposable"},
            {"word": "替代品", "pinyin": "tìdàipǐn", "meaning": "alternatives/substitutes"},
        ],
        "model_answer": "图中的一次性塑料杯和吸管是重大的环境污染来源。这些塑料难以分解，会在自然界中存在数百年，污染海洋和伤害动物。为了减少使用一次性塑料，我们可以自带水瓶和餐具，选择使用竹子或不锈钢吸管等替代品。新加坡也已开始对一次性塑料征收额外费用，以鼓励大家改变习惯。",
        "followup_questions": ["政府措施和个人行动哪个更重要？为什么？"],
        "scoring_hints": ["identifies pollution problem", "gives practical alternatives", "policy awareness"],
    },
    {
        "id": "Q39", "level": "P4", "topic": "环境",
        "emoji": "🐠",
        "image_url": "https://images.unsplash.com/photo-1546026423-cc4642628d2b?w=600",
        "image_caption": "珊瑚礁",
        "question_zh": "图中的地方是哪里？为什么珊瑚礁值得我们保护？",
        "question_en": "What is shown? Why are coral reefs worth protecting?",
        "vocab": ["珊瑚礁", "海洋生物", "多样性", "漂白", "脆弱"],
        "vocab_with_pinyin": [
            {"word": "珊瑚礁", "pinyin": "shānhújiāo", "meaning": "coral reef"},
            {"word": "多样性", "pinyin": "duōyàngxìng", "meaning": "diversity"},
        ],
        "model_answer": "图中是美丽的珊瑚礁，里面住着各种五颜六色的鱼类和海洋生物。珊瑚礁是海洋中生物多样性最丰富的生态系统，被称为海洋中的热带雨林。但是由于海水温度升高和污染，很多珊瑚礁正在死亡。我们要保护珊瑚礁，因为它对整个海洋生态系统非常重要。",
        "followup_questions": ["你去过哪些自然保护区？有什么感受？"],
        "scoring_hints": ["identifies coral reef", "explains importance", "threats to coral"],
    },
    {
        "id": "Q40", "level": "P5", "topic": "环境",
        "emoji": "🚲",
        "image_url": "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=600",
        "image_caption": "骑自行车出行",
        "question_zh": "骑自行车出行有什么好处？你认为新加坡应该更多推广这种出行方式吗？",
        "question_en": "What are the benefits of cycling? Should Singapore promote it more?",
        "vocab": ["自行车", "绿色出行", "减少", "排放", "健康"],
        "vocab_with_pinyin": [
            {"word": "绿色出行", "pinyin": "lǜsè chūxíng", "meaning": "green transportation"},
            {"word": "排放", "pinyin": "páifàng", "meaning": "emissions"},
        ],
        "model_answer": "骑自行车出行好处多多：首先，它不排放废气，是一种环保的绿色出行方式；其次，骑车也是一种锻炼，有益健康；此外，还能减少交通堵塞。我认为新加坡应该更多推广骑车，比如建设更多自行车道，让骑车变得更安全方便。已经有越来越多的新加坡人选择骑车上班了。",
        "followup_questions": ["骑车出行在新加坡面临哪些挑战？"],
        "scoring_hints": ["gives multiple benefits", "local context", "balanced view on challenges"],
    },

    # ══════════════════════════════════════════════════════════
    # TOPIC: 健康 HEALTH  (Q41-Q50)
    # ══════════════════════════════════════════════════════════
    {
        "id": "Q41", "level": "P4", "topic": "健康",
        "emoji": "🥗",
        "image_url": "https://images.unsplash.com/photo-1512621776951-a57141f2eefd?w=600",
        "image_caption": "健康饮食",
        "question_zh": "图中有什么食物？健康饮食对我们有什么好处？",
        "question_en": "What foods are shown? What are the benefits of healthy eating?",
        "vocab": ["健康饮食", "营养均衡", "蔬菜水果", "维生素", "免疫力"],
        "vocab_with_pinyin": [
            {"word": "营养均衡", "pinyin": "yíngyǎng jūnhéng", "meaning": "balanced nutrition"},
            {"word": "免疫力", "pinyin": "miǎnyìlì", "meaning": "immunity"},
        ],
        "model_answer": "图中有各种颜色的蔬菜和水果，看起来非常营养丰富。健康饮食对我们非常重要：它能提供身体所需的维生素和矿物质，增强免疫力，让我们不容易生病。我每天都会努力吃各种蔬菜，因为我知道均衡饮食能让我有足够的精力学习和玩耍。",
        "followup_questions": ["你认为学校食堂的食物足够健康吗？"],
        "scoring_hints": ["describes healthy food", "lists benefits", "personal habits"],
    },
    {
        "id": "Q42", "level": "P5", "topic": "健康",
        "emoji": "🏃",
        "image_url": "https://images.unsplash.com/photo-1571019614242-c5c5dee9f50b?w=600",
        "image_caption": "运动锻炼",
        "question_zh": "图中的人在做什么运动？定期运动对身体有什么好处？",
        "question_en": "What exercise is shown? What are the benefits of regular exercise?",
        "vocab": ["锻炼", "体力", "坚持", "减压", "专注力"],
        "vocab_with_pinyin": [
            {"word": "坚持", "pinyin": "jiānchí", "meaning": "to persist/persevere"},
            {"word": "减压", "pinyin": "jiǎnyā", "meaning": "to reduce stress"},
        ],
        "model_answer": "图中的人在跑步锻炼，这是一种很好的有氧运动。定期运动的好处有很多：可以增强体力和心肺功能，帮助控制体重，减轻学习压力，还能提高专注力，让我们在学习时更有效率。我每周都会去学校操场跑步，感觉运动过后精神特别好。",
        "followup_questions": ["你最喜欢什么运动？坚持运动有什么困难？"],
        "scoring_hints": ["identifies running", "multiple benefits", "personal experience"],
    },
    {
        "id": "Q43", "level": "P4", "topic": "健康",
        "emoji": "😴",
        "image_url": "https://images.unsplash.com/photo-1541781774459-bb2af2f05b55?w=600",
        "image_caption": "充足睡眠",
        "question_zh": "图中的孩子在做什么？充足的睡眠为什么重要？",
        "question_en": "What is the child doing? Why is adequate sleep important?",
        "vocab": ["睡眠", "休息", "精力", "成长", "专注"],
        "vocab_with_pinyin": [
            {"word": "睡眠", "pinyin": "shuìmián", "meaning": "sleep"},
            {"word": "精力", "pinyin": "jīnglì", "meaning": "energy/vigour"},
        ],
        "model_answer": "图中的孩子在睡觉。充足的睡眠对儿童非常重要：睡眠期间，身体会分泌生长激素，帮助我们成长；大脑也会整理当天学到的知识；足够的睡眠还能让我们第二天精力充沛，在学校专心学习。医生建议小学生每天要睡九到十个小时。",
        "followup_questions": ["你每天能睡够几个小时？有什么影响你睡眠的因素？"],
        "scoring_hints": ["explains sleep importance", "mentions growth and learning", "specific hours"],
    },
    {
        "id": "Q44", "level": "P6", "topic": "健康",
        "emoji": "📱",
        "image_url": "https://images.unsplash.com/photo-1555421689-491a97ff2040?w=600",
        "image_caption": "长时间使用手机",
        "question_zh": "长时间使用手机对健康有什么影响？你认为应该如何正确使用手机？",
        "question_en": "What health effects does prolonged phone use have? How should phones be used wisely?",
        "vocab": ["视力", "姿势", "上瘾", "节制", "平衡"],
        "vocab_with_pinyin": [
            {"word": "视力", "pinyin": "shìlì", "meaning": "eyesight/vision"},
            {"word": "上瘾", "pinyin": "shàngyǐn", "meaning": "addiction"},
        ],
        "model_answer": "长时间使用手机对健康有多方面的影响：首先，长时间盯着屏幕会损害视力；其次，低头看手机会导致颈椎问题；此外，手机游戏和社交媒体容易让人上瘾，影响睡眠和学习。我认为我们应该控制使用手机的时间，每隔一段时间就要让眼睛休息，睡前一小时不看手机。",
        "followup_questions": ["你认为家长应该限制孩子使用手机的时间吗？"],
        "scoring_hints": ["multiple health impacts", "practical solutions", "balanced view"],
    },
    {
        "id": "Q45", "level": "P5", "topic": "健康",
        "emoji": "🧘",
        "image_url": "https://images.unsplash.com/photo-1544367567-0f2fcb009e0b?w=600",
        "image_caption": "冥想放松",
        "question_zh": "图中的人在做什么？心理健康对我们有多重要？",
        "question_en": "What is the person doing? How important is mental health?",
        "vocab": ["心理健康", "冥想", "压力", "情绪", "放松"],
        "vocab_with_pinyin": [
            {"word": "心理健康", "pinyin": "xīnlǐ jiànkāng", "meaning": "mental health"},
            {"word": "冥想", "pinyin": "míngxiǎng", "meaning": "meditation"},
        ],
        "model_answer": "图中的人在冥想，通过专注呼吸来放松身心。心理健康与身体健康同样重要。现代人，包括学生，都面临很多压力，如果不懂得管理情绪和压力，可能会影响日常生活和学习。我们可以通过运动、与朋友倾诉或培养兴趣爱好来保持心理健康。",
        "followup_questions": ["你在压力大的时候会怎么调节自己的情绪？"],
        "scoring_hints": ["identifies meditation", "discusses mental health importance", "coping strategies"],
    },
    {
        "id": "Q46", "level": "P4", "topic": "健康",
        "emoji": "🦷",
        "image_url": "https://images.unsplash.com/photo-1609840114035-3c981b782dfe?w=600",
        "image_caption": "刷牙",
        "question_zh": "图中的孩子在做什么？我们应该怎样照顾好我们的牙齿？",
        "question_en": "What is the child doing? How should we take care of our teeth?",
        "vocab": ["刷牙", "口腔卫生", "蛀牙", "定期", "检查"],
        "vocab_with_pinyin": [
            {"word": "口腔卫生", "pinyin": "kǒuqiāng wèishēng", "meaning": "oral hygiene"},
            {"word": "蛀牙", "pinyin": "zhùyá", "meaning": "tooth decay/cavities"},
        ],
        "model_answer": "图中的孩子在刷牙，这是非常好的卫生习惯。照顾好牙齿很重要，我们应该每天早晚各刷一次牙，每次刷两分钟，饭后漱口，减少吃糖和甜食，定期去看牙医检查。如果不保持口腔卫生，就会长蛀牙，那会非常痛！",
        "followup_questions": ["你每天刷几次牙？你有没有去过牙医？"],
        "scoring_hints": ["identifies brushing teeth", "gives oral care tips", "consequences of not caring"],
    },
    {
        "id": "Q47", "level": "P5", "topic": "健康",
        "emoji": "🍔",
        "image_url": "https://images.unsplash.com/photo-1568901346375-23c9450c58cd?w=600",
        "image_caption": "垃圾食品",
        "question_zh": "经常吃这类食物对健康有什么影响？你认为偶尔吃可以吗？",
        "question_en": "What are the health effects of eating such food often? Is it ok to eat it occasionally?",
        "vocab": ["垃圾食品", "肥胖", "糖尿病", "节制", "偶尔"],
        "vocab_with_pinyin": [
            {"word": "垃圾食品", "pinyin": "lājī shípǐn", "meaning": "junk food"},
            {"word": "肥胖", "pinyin": "féipàng", "meaning": "obesity"},
        ],
        "model_answer": "图中是汉堡、薯条等垃圾食品，虽然看起来很美味，但营养价值很低，含有大量的油脂、盐和糖。经常吃这类食物会导致肥胖、高血压、糖尿病等健康问题。我认为偶尔吃一次是可以的，但不能把它当作日常饮食。凡事都要有节制，饮食也一样。",
        "followup_questions": ["你每周会吃多少次垃圾食品？你认为这样健康吗？"],
        "scoring_hints": ["discusses health risks", "balanced view on occasional eating", "moderation message"],
    },
    {
        "id": "Q48", "level": "P4", "topic": "健康",
        "emoji": "🩺",
        "image_url": "https://images.unsplash.com/photo-1579684385127-1ef15d508118?w=600",
        "image_caption": "看医生",
        "question_zh": "图中的孩子在做什么？生病了应该怎么办？",
        "question_en": "What is the child doing? What should you do when you are sick?",
        "vocab": ["医生", "发烧", "药物", "休息", "康复"],
        "vocab_with_pinyin": [
            {"word": "发烧", "pinyin": "fāshāo", "meaning": "fever"},
            {"word": "康复", "pinyin": "kāngfù", "meaning": "to recover"},
        ],
        "model_answer": "图中的孩子正在看医生，医生正在为他检查身体。生病了应该告诉父母，然后去看医生。我们要按时吃药，多喝水，好好休息，不要硬撑着去上学，免得病情加重或传染给同学。我上次发烧的时候，妈妈陪我去看医生，吃了药之后很快就好了。",
        "followup_questions": ["生病时你是怎么照顾自己的？"],
        "scoring_hints": ["describes seeing doctor", "gives steps when sick", "personal experience"],
    },
    {
        "id": "Q49", "level": "P6", "topic": "健康",
        "emoji": "🧬",
        "image_url": "https://images.unsplash.com/photo-1576091160399-112ba8d25d1d?w=600",
        "image_caption": "医学研究",
        "question_zh": "医学的进步对人类健康有什么影响？",
        "question_en": "How has medical progress affected human health?",
        "vocab": ["医学", "疫苗", "手术", "寿命", "预防"],
        "vocab_with_pinyin": [
            {"word": "疫苗", "pinyin": "yìmiáo", "meaning": "vaccine"},
            {"word": "寿命", "pinyin": "shòumìng", "meaning": "lifespan"},
        ],
        "model_answer": "医学的进步对人类健康有巨大的影响。疫苗的发明消灭了许多曾经夺走无数生命的传染病；先进的外科手术技术能够治愈以前无法治好的疾病；医学研究也让人类的平均寿命大大延长。新加坡拥有先进的医疗体系，是全球医疗水平最高的国家之一。",
        "followup_questions": ["你认为人类最重要的医学发现是什么？为什么？"],
        "scoring_hints": ["gives specific examples of medical progress", "Singapore context", "impact on lifespan"],
    },
    {
        "id": "Q50", "level": "P5", "topic": "健康",
        "emoji": "🚬",
        "image_url": "https://images.unsplash.com/photo-1592434134753-a70baf7979d5?w=600",
        "image_caption": "吸烟危害",
        "question_zh": "吸烟对健康有什么危害？你会怎么劝阻身边的人不要吸烟？",
        "question_en": "What are the health harms of smoking? How would you discourage others from smoking?",
        "vocab": ["吸烟", "危害", "癌症", "上瘾", "劝阻"],
        "vocab_with_pinyin": [
            {"word": "危害", "pinyin": "wēihài", "meaning": "harm/hazard"},
            {"word": "劝阻", "pinyin": "quànzǔ", "meaning": "to dissuade/discourage"},
        ],
        "model_answer": "吸烟对健康危害极大，会导致肺癌、心脏病等严重疾病，而且烟草含有尼古丁，很容易上瘾，难以戒除。如果我的朋友或家人想要吸烟，我会用健康知识来劝阻他们，告诉他们吸烟的危害，也可以建议他们用运动或其他健康方式来减压。新加坡政府也有很多禁烟政策来保护公众健康。",
        "followup_questions": ["新加坡有哪些控制吸烟的法规？你认为有效吗？"],
        "scoring_hints": ["explains smoking harms", "gives persuasive approach", "Singapore policy"],
    },

    # ══════════════════════════════════════════════════════════
    # TOPIC: 社区 COMMUNITY  (Q51-Q60)
    # ══════════════════════════════════════════════════════════
    {
        "id": "Q51", "level": "P4", "topic": "社区",
        "emoji": "🤲",
        "image_url": "https://images.unsplash.com/photo-1559027615-cd4628902d4a?w=600",
        "image_caption": "义工服务",
        "question_zh": "图中的人在做什么？做义工对社区有什么贡献？",
        "question_en": "What are people doing? How do volunteers contribute to the community?",
        "vocab": ["义工", "贡献", "无私", "社区", "帮助"],
        "vocab_with_pinyin": [
            {"word": "义工", "pinyin": "yìgōng", "meaning": "volunteer"},
            {"word": "无私", "pinyin": "wúsī", "meaning": "selfless"},
        ],
        "model_answer": "图中的人们在做义工，帮助社区里有需要的人。做义工对社区很有贡献：义工们的无私服务能帮助老人、残障人士和有困难的家庭。做义工也让我们学会感恩，明白不是每个人的生活都像我们一样轻松。我曾经参加学校组织的义工活动，为老人院的爷爷奶奶表演，他们看起来很开心。",
        "followup_questions": ["你参加过什么义工活动？有什么感受？"],
        "scoring_hints": ["describes volunteering", "explains contribution", "personal experience"],
    },
    {
        "id": "Q52", "level": "P5", "topic": "社区",
        "emoji": "🏘️",
        "image_url": "https://images.unsplash.com/photo-1580587771525-78b9dba3b914?w=600",
        "image_caption": "组屋邻里",
        "question_zh": "图中展示了什么？好邻居对社区生活有什么重要性？",
        "question_en": "What is shown? Why are good neighbours important for community life?",
        "vocab": ["邻居", "守望相助", "和睦", "信任", "互助"],
        "vocab_with_pinyin": [
            {"word": "守望相助", "pinyin": "shǒuwàng xiāngzhù", "meaning": "to look out for each other"},
            {"word": "和睦", "pinyin": "hémù", "meaning": "harmonious"},
        ],
        "model_answer": "图中是新加坡的组屋，很多家庭住在同一栋楼里。好邻居对社区生活非常重要，邻居之间互相守望相助，能让社区更安全和谐。在新加坡的组屋社区，邻居们互相帮忙照看孩子、分享食物，这种邻里精神很值得珍惜。我们家的邻居就非常友善，常常互相帮助。",
        "followup_questions": ["在高楼林立的新加坡，你认为邻里关系为什么越来越疏远？"],
        "scoring_hints": ["describes HDB community", "explains importance of neighbours", "personal example"],
    },
    {
        "id": "Q53", "level": "P4", "topic": "社区",
        "emoji": "🚌",
        "image_url": "https://images.unsplash.com/photo-1544620347-c4fd4a3d5957?w=600",
        "image_caption": "公共交通",
        "question_zh": "图中是什么交通工具？使用公共交通有什么好处？",
        "question_en": "What transport is shown? What are the benefits of public transport?",
        "vocab": ["公共交通", "巴士", "地铁", "环保", "方便"],
        "vocab_with_pinyin": [
            {"word": "公共交通", "pinyin": "gōnggòng jiāotōng", "meaning": "public transport"},
            {"word": "方便", "pinyin": "fāngbiàn", "meaning": "convenient"},
        ],
        "model_answer": "图中是公共巴士，是新加坡最常见的公共交通工具之一。使用公共交通好处很多：可以减少私家车数量，缓解交通堵塞；排放的废气比许多私家车加起来更少，对环境更友好；公共交通也相对便宜，大家都负担得起。我上学每天都坐地铁，觉得非常方便。",
        "followup_questions": ["你认为新加坡的公共交通系统有哪些可以改进的地方？"],
        "scoring_hints": ["identifies public transport", "multiple benefits", "local context"],
    },
    {
        "id": "Q54", "level": "P6", "topic": "社区",
        "emoji": "👴",
        "image_url": "https://images.unsplash.com/photo-1516307365426-bea591f05011?w=600",
        "image_caption": "关爱老人",
        "question_zh": "新加坡社会正在老龄化。我们应该怎样关爱年长者？",
        "question_en": "Singapore is aging. How should we care for the elderly?",
        "vocab": ["老龄化", "年长者", "尊重", "孤独", "照顾"],
        "vocab_with_pinyin": [
            {"word": "老龄化", "pinyin": "lǎolínghuà", "meaning": "aging population"},
            {"word": "尊重", "pinyin": "zūnzhòng", "meaning": "respect"},
        ],
        "model_answer": "新加坡的老龄化问题日益严重，越来越多的年长者需要社会的关注。我认为我们应该从多方面关爱年长者：在家里，子女应该多陪伴父母和祖父母；在社区里，我们可以帮助独居老人做家务或陪他们聊天；政府也应该提供更多老年服务设施。最重要的是，我们要尊重年长者，不要因为他们年纪大就忽视他们。",
        "followup_questions": ["你认为把老人送去老人院是孝顺的行为吗？"],
        "scoring_hints": ["understands aging issue", "gives solutions at different levels", "shows empathy"],
    },
    {
        "id": "Q55", "level": "P5", "topic": "社区",
        "emoji": "🏥",
        "image_url": "https://images.unsplash.com/photo-1519494026892-80bbd2d6fd0d?w=600",
        "image_caption": "医院",
        "question_zh": "图中是什么地方？医疗工作者对社会有什么贡献？",
        "question_en": "What place is shown? What do healthcare workers contribute to society?",
        "vocab": ["医疗", "贡献", "牺牲", "奉献", "救死扶伤"],
        "vocab_with_pinyin": [
            {"word": "奉献", "pinyin": "fèngxiàn", "meaning": "to dedicate oneself"},
            {"word": "救死扶伤", "pinyin": "jiùsǐ fúshāng", "meaning": "to save lives and heal the injured"},
        ],
        "model_answer": "图中是医院，医生和护士在这里救死扶伤。医疗工作者对社会的贡献是巨大的，他们经常工作很长时间，有时还要冒着感染疾病的风险来照顾病人。在新冠疫情期间，医疗工作者的奉献精神令人感动。我非常尊重和感激所有的医疗工作者，我的梦想之一就是将来成为一名医生。",
        "followup_questions": ["疫情让你对医疗工作者有了什么新的认识？"],
        "scoring_hints": ["identifies hospital", "praises healthcare workers", "COVID-19 reference"],
    },
    {
        "id": "Q56", "level": "P4", "topic": "社区",
        "emoji": "👮",
        "image_url": "https://images.unsplash.com/photo-1605726310022-ff4b51bffb65?w=600",
        "image_caption": "警察",
        "question_zh": "图中是谁？他们对社区有什么重要性？",
        "question_en": "Who is shown? Why are they important to the community?",
        "vocab": ["警察", "安全", "执法", "保护", "犯罪"],
        "vocab_with_pinyin": [
            {"word": "执法", "pinyin": "zhífǎ", "meaning": "law enforcement"},
            {"word": "犯罪", "pinyin": "fànzuì", "meaning": "crime"},
        ],
        "model_answer": "图中是警察，他们是维护社会治安的重要人员。警察的工作非常重要：他们每天巡逻，让市民感到安全；当有人遇到危险时，警察会第一时间赶到；他们也调查犯罪，让违法的人受到应有的惩处。新加坡是一个治安很好的国家，这和我们的警察队伍的努力是分不开的。",
        "followup_questions": ["你遇到危险的时候应该怎么寻求帮助？"],
        "scoring_hints": ["identifies police", "explains police role", "Singapore safety context"],
    },
    {
        "id": "Q57", "level": "P6", "topic": "社区",
        "emoji": "🌐",
        "image_url": "https://images.unsplash.com/photo-1529107386315-e1a2ed48a620?w=600",
        "image_caption": "新加坡多元文化",
        "question_zh": "新加坡是一个多元种族的国家。多元文化对新加坡有什么好处和挑战？",
        "question_en": "Singapore is a multi-racial country. What are the benefits and challenges of multiculturalism?",
        "vocab": ["多元文化", "包容", "凝聚力", "误解", "沟通"],
        "vocab_with_pinyin": [
            {"word": "包容", "pinyin": "bāoróng", "meaning": "tolerance/inclusiveness"},
            {"word": "凝聚力", "pinyin": "níngjùlì", "meaning": "cohesion"},
        ],
        "model_answer": "多元文化对新加坡有很多好处：不同文化的碰撞带来了丰富的美食、艺术和传统；多元化的思维方式也让新加坡更具创新能力；我们能从不同文化中相互学习，开拓视野。挑战方面，不同文化背景的人可能因为误解而产生冲突，因此我们需要多沟通、多包容，维护社会和谐。",
        "followup_questions": ["如果你的朋友对某个种族有偏见，你会怎么做？"],
        "scoring_hints": ["balanced benefits and challenges", "uses relevant vocabulary", "gives examples"],
    },
    {
        "id": "Q58", "level": "P4", "topic": "社区",
        "emoji": "🗳️",
        "image_url": "https://images.unsplash.com/photo-1540910419892-4a36d2c3266c?w=600",
        "image_caption": "公民活动",
        "question_zh": "做一个好公民有哪些责任？",
        "question_en": "What are the responsibilities of a good citizen?",
        "vocab": ["公民", "责任", "守法", "关心", "贡献"],
        "vocab_with_pinyin": [
            {"word": "公民", "pinyin": "gōngmín", "meaning": "citizen"},
            {"word": "守法", "pinyin": "shǒufǎ", "meaning": "to abide by the law"},
        ],
        "model_answer": "做一个好公民有很多责任。首先，我们要遵守法律，不做违法的事。其次，我们要关心社区，爱护公共设施，不乱丢垃圾。第三，我们要帮助有需要的人，积极参与社区活动。第四，我们要尊重不同种族和宗教的人。我虽然还是小学生，但我也能从小事做起，做一个负责任的小公民。",
        "followup_questions": ["你认为小学生能为社区做什么贡献？"],
        "scoring_hints": ["lists multiple responsibilities", "concrete examples", "age-appropriate actions"],
    },
    {
        "id": "Q59", "level": "P5", "topic": "社区",
        "emoji": "🏗️",
        "image_url": "https://images.unsplash.com/photo-1486325212027-8081e485255e?w=600",
        "image_caption": "城市建设",
        "question_zh": "新加坡的城市规划有什么特点？这对居民的生活有什么影响？",
        "question_en": "What are features of Singapore's urban planning? How does it affect residents' lives?",
        "vocab": ["城市规划", "公共设施", "绿化", "便利", "生活质量"],
        "vocab_with_pinyin": [
            {"word": "城市规划", "pinyin": "chéngshì guīhuà", "meaning": "urban planning"},
            {"word": "生活质量", "pinyin": "shēnghuó zhìliàng", "meaning": "quality of life"},
        ],
        "model_answer": "新加坡的城市规划非常周密，有很多特点：组屋围绕着购物中心、学校和公园建设，居民生活非常便利；政府非常重视绿化，在城市中种植了大量的树木和花草；公共交通网络发达，覆盖全岛。这些都大大提高了新加坡居民的生活质量，让新加坡成为宜居城市。",
        "followup_questions": ["你希望未来的新加坡城市规划有什么改变？"],
        "scoring_hints": ["specific urban planning features", "impact on residents", "forward-looking view"],
    },
    {
        "id": "Q60", "level": "P6", "topic": "社区",
        "emoji": "💻",
        "image_url": "https://images.unsplash.com/photo-1518770660439-4636190af475?w=600",
        "image_caption": "智慧城市",
        "question_zh": "新加坡正在成为一个智慧城市。科技如何改善市民的生活？",
        "question_en": "Singapore is becoming a smart city. How does technology improve citizens' lives?",
        "vocab": ["智慧城市", "科技", "效率", "创新", "数码"],
        "vocab_with_pinyin": [
            {"word": "智慧城市", "pinyin": "zhìhuì chéngshì", "meaning": "smart city"},
            {"word": "数码", "pinyin": "shùmǎ", "meaning": "digital"},
        ],
        "model_answer": "新加坡正在积极发展智慧城市，科技正在改善市民生活的方方面面。比如，手机应用程序让我们可以轻松查询巴士到站时间；电子政务让我们不必亲自到政府机构办事；智能交通系统减少了交通堵塞；电子支付也让购物更便利。我相信随着科技的进步，新加坡市民的生活会越来越方便。",
        "followup_questions": ["科技进步可能带来哪些社会问题？怎么解决？"],
        "scoring_hints": ["concrete smart city examples", "benefits to citizens", "forward-looking perspective"],
    },

    # ══════════════════════════════════════════════════════════
    # TOPIC: 食物 FOOD  (Q61-Q70)
    # ══════════════════════════════════════════════════════════
    {
        "id": "Q61", "level": "P4", "topic": "食物",
        "emoji": "🍜",
        "image_url": "https://images.unsplash.com/photo-1569718212165-3a8278d5f624?w=600",
        "image_caption": "新加坡美食",
        "question_zh": "图中是什么新加坡美食？你最喜欢哪种新加坡食物？",
        "question_en": "What Singapore food is shown? What is your favourite Singapore dish?",
        "vocab": ["美食", "特色", "口味", "新鲜", "文化"],
        "vocab_with_pinyin": [
            {"word": "特色", "pinyin": "tèsè", "meaning": "characteristic/speciality"},
            {"word": "口味", "pinyin": "kǒuwèi", "meaning": "taste/flavour"},
        ],
        "model_answer": "图中是新加坡的特色美食叉烧面，面条劲道，叉烧香甜，配上秘制酱料，非常美味。我最喜欢的新加坡食物是海南鸡饭，鸡肉嫩滑，米饭香软，蘸着姜蓉和辣椒酱，让人回味无穷。新加坡的美食体现了多元种族文化的融合，是我们的文化骄傲。",
        "followup_questions": ["新加坡的多元种族文化怎样影响了我们的饮食？"],
        "scoring_hints": ["identifies the food", "describes favourite dish with details", "cultural connection"],
    },
    {
        "id": "Q62", "level": "P4", "topic": "食物",
        "emoji": "🥘",
        "image_url": "https://images.unsplash.com/photo-1585032226651-759b368d7246?w=600",
        "image_caption": "小贩中心",
        "question_zh": "图中是什么地方？小贩中心对新加坡文化有什么意义？",
        "question_en": "What place is shown? What is the cultural significance of hawker centres?",
        "vocab": ["小贩中心", "文化遗产", "多样", "平价", "传统"],
        "vocab_with_pinyin": [
            {"word": "文化遗产", "pinyin": "wénhuà yíchǎn", "meaning": "cultural heritage"},
            {"word": "平价", "pinyin": "píngjià", "meaning": "affordable"},
        ],
        "model_answer": "图中是新加坡的小贩中心，这是我们国家独特的饮食文化。小贩中心是各种种族美食的聚集地，在一个地方就能吃到华族、马来族、印度族和其他各种美食，价钱也非常实惠。新加坡的小贩文化已被列为联合国非物质文化遗产，是我们的骄傲。",
        "followup_questions": ["你最喜欢去哪个小贩中心？为什么？"],
        "scoring_hints": ["describes hawker centre", "cultural significance", "UNESCO heritage"],
    },
    {
        "id": "Q63", "level": "P5", "topic": "食物",
        "emoji": "🌾",
        "image_url": "https://images.unsplash.com/photo-1574323347407-f5e1ad6d020b?w=600",
        "image_caption": "食物浪费",
        "question_zh": "图中展示了什么问题？我们应该怎样减少食物浪费？",
        "question_en": "What problem is shown? How should we reduce food waste?",
        "vocab": ["食物浪费", "珍惜", "剩菜", "饥饿", "节约"],
        "vocab_with_pinyin": [
            {"word": "珍惜", "pinyin": "zhēnxī", "meaning": "to cherish/value"},
            {"word": "饥饿", "pinyin": "jī'è", "meaning": "hunger/starvation"},
        ],
        "model_answer": "图中展示了大量被丢弃的食物，这是严重的食物浪费现象。世界上还有很多人在忍饥挨饿，我们却浪费食物，实在非常可惜。为了减少食物浪费，我们要适量购买食物，吃多少买多少；不要点太多饮食，要把食物吃完；家里的剩菜也要好好保存。我们要从小养成珍惜食物的好习惯。",
        "followup_questions": ["新加坡每年浪费多少食物？这个数字令你震惊吗？"],
        "scoring_hints": ["identifies food waste problem", "empathy for world hunger", "practical solutions"],
    },
    {
        "id": "Q64", "level": "P4", "topic": "食物",
        "emoji": "🍱",
        "image_url": "https://images.unsplash.com/photo-1547592166-23ac45744acd?w=600",
        "image_caption": "日本便当",
        "question_zh": "图中是什么食物？你喜欢吃哪个国家的食物？为什么？",
        "question_en": "What food is shown? Which country's food do you enjoy eating? Why?",
        "vocab": ["日本料理", "风味", "新鲜", "精致", "外国"],
        "vocab_with_pinyin": [
            {"word": "精致", "pinyin": "jīngzhì", "meaning": "refined/exquisite"},
            {"word": "风味", "pinyin": "fēngwèi", "meaning": "flavour/taste"},
        ],
        "model_answer": "图中是日本便当，里面有寿司、炸鸡和蔬菜，摆放得非常精致漂亮。我非常喜欢日本料理，因为日本食物非常注重食材的新鲜，口味清淡而美味。日本拉面、寿司和天妇罗都是我的最爱。品尝不同国家的食物也是了解不同文化的好方法。",
        "followup_questions": ["你有没有学过如何烹饪某种菜肴？"],
        "scoring_hints": ["identifies food", "expresses preference with reasons", "cultural appreciation"],
    },
    {
        "id": "Q65", "level": "P6", "topic": "食物",
        "emoji": "🌿",
        "image_url": "https://images.unsplash.com/photo-1505253716362-afaea1d3d1af?w=600",
        "image_caption": "素食",
        "question_zh": "素食越来越受欢迎。你认为吃素食有什么好处？你会考虑吃素食吗？",
        "question_en": "Vegetarianism is growing. What are the benefits? Would you consider going vegetarian?",
        "vocab": ["素食", "环保", "健康", "动物福利", "选择"],
        "vocab_with_pinyin": [
            {"word": "素食", "pinyin": "sùshí", "meaning": "vegetarian food"},
            {"word": "动物福利", "pinyin": "dòngwù fúlì", "meaning": "animal welfare"},
        ],
        "model_answer": "素食越来越受人欢迎，有很多好处：首先，素食对健康有益，可以降低患心脏病和糖尿病的风险；其次，减少肉食消费能降低畜牧业的碳排放，对环境更友好；第三，吃素食也体现了对动物的尊重。我会考虑减少吃肉，但不一定完全吃素，因为均衡饮食也很重要。",
        "followup_questions": ["你认为政府应该鼓励人们减少吃肉吗？"],
        "scoring_hints": ["multiple benefits of vegetarianism", "environmental angle", "balanced personal view"],
    },
    {
        "id": "Q66", "level": "P4", "topic": "食物",
        "emoji": "🍰",
        "image_url": "https://images.unsplash.com/photo-1565958011703-44f9829ba187?w=600",
        "image_caption": "烘焙甜点",
        "question_zh": "图中的甜点是什么？你会烘焙食物吗？",
        "question_en": "What desserts are shown? Do you know how to bake?",
        "vocab": ["烘焙", "食谱", "材料", "甜点", "技巧"],
        "vocab_with_pinyin": [
            {"word": "烘焙", "pinyin": "hōngbèi", "meaning": "baking"},
            {"word": "食谱", "pinyin": "shípǔ", "meaning": "recipe"},
        ],
        "model_answer": "图中是各种美味的蛋糕和甜点，颜色和形状都非常漂亮。我会基本的烘焙，比如做饼干和纸杯蛋糕。烘焙需要按照食谱准确量好材料，非常考验耐心和细心。我最喜欢在节假日和妈妈一起烘焙，做出来的食物和家人分享，感觉特别有成就感。",
        "followup_questions": ["学习烹饪对小孩子有什么好处？"],
        "scoring_hints": ["describes desserts", "shares baking experience", "value of cooking skills"],
    },
    {
        "id": "Q67", "level": "P5", "topic": "食物",
        "emoji": "🥬",
        "image_url": "https://images.unsplash.com/photo-1464226184884-fa280b87c399?w=600",
        "image_caption": "城市农场",
        "question_zh": "图中展示了什么？城市农业对新加坡有什么意义？",
        "question_en": "What is shown? What does urban farming mean for Singapore?",
        "vocab": ["城市农业", "粮食安全", "本地产", "可持续", "创新"],
        "vocab_with_pinyin": [
            {"word": "粮食安全", "pinyin": "liángshí ānquán", "meaning": "food security"},
            {"word": "可持续", "pinyin": "kě chíxù", "meaning": "sustainable"},
        ],
        "model_answer": "图中是城市农场，在高楼大厦或室内种植蔬菜和水果。城市农业对新加坡意义重大，因为新加坡土地有限，大部分食物需要进口。政府推动'30·30愿景'，目标是到2030年，本地生产满足三成的营养需求。城市农业能提升粮食安全，减少对进口的依赖，是新加坡的创新解决方案。",
        "followup_questions": ["你认为城市农业能解决全球粮食问题吗？"],
        "scoring_hints": ["describes urban farm", "food security awareness", "Singapore policy knowledge"],
    },
    {
        "id": "Q68", "level": "P4", "topic": "食物",
        "emoji": "🦀",
        "image_url": "https://images.unsplash.com/photo-1569718212165-3a8278d5f624?w=600",
        "image_caption": "辣椒螃蟹",
        "question_zh": "辣椒螃蟹是新加坡的国菜之一。介绍一下这道菜的特点。",
        "question_en": "Chilli crab is one of Singapore's national dishes. Describe its features.",
        "vocab": ["辣椒螃蟹", "酱汁", "鲜美", "特色", "国菜"],
        "vocab_with_pinyin": [
            {"word": "辣椒螃蟹", "pinyin": "làjiāo pángxiè", "meaning": "chilli crab"},
            {"word": "鲜美", "pinyin": "xiānměi", "meaning": "fresh and delicious"},
        ],
        "model_answer": "辣椒螃蟹是新加坡最具代表性的美食之一，曾被CNN评为世界最美味的食物之一。这道菜的特点是螃蟹鲜美，配上红色的酸辣番茄酱，香气扑鼻，口感丰富。吃辣椒螃蟹的时候，还要用炸馒头蘸酱汁，非常美味。这道菜体现了新加坡融合多元文化的饮食特色。",
        "followup_questions": ["你最近一次吃辣椒螃蟹是什么时候？在哪里吃的？"],
        "scoring_hints": ["describes chilli crab", "mentions specific characteristics", "cultural pride"],
    },
    {
        "id": "Q69", "level": "P5", "topic": "食物",
        "emoji": "🍵",
        "image_url": "https://images.unsplash.com/photo-1556679343-c7306c1976bc?w=600",
        "image_caption": "传统茶文化",
        "question_zh": "图中展示了什么？华人的茶文化有什么特点？",
        "question_en": "What is shown? What are the features of Chinese tea culture?",
        "vocab": ["茶文化", "功夫茶", "礼节", "品茗", "传统"],
        "vocab_with_pinyin": [
            {"word": "品茗", "pinyin": "pǐnmíng", "meaning": "to taste/appreciate tea"},
            {"word": "功夫茶", "pinyin": "gōngfū chá", "meaning": "gongfu tea ceremony"},
        ],
        "model_answer": "图中展示了华人的茶文化，有精致的茶具和各种茶叶。华人的茶文化历史悠久，有很多特点：品茗不只是喝茶，更是一种艺术和礼节；不同种类的茶有不同的冲泡方式和口味；茶道也代表着待客之道，用茶来表达尊重和热情。我的祖父非常喜欢喝茶，经常教我辨别不同茶叶的香气。",
        "followup_questions": ["你觉得年轻人还有兴趣学习传统茶道吗？为什么？"],
        "scoring_hints": ["describes tea culture", "explains features", "personal connection"],
    },
    {
        "id": "Q70", "level": "P6", "topic": "食物",
        "emoji": "🧪",
        "image_url": "https://images.unsplash.com/photo-1547592166-23ac45744acd?w=600",
        "image_caption": "食品科技",
        "question_zh": "人造肉等食品科技会改变我们的饮食方式吗？你对此有什么看法？",
        "question_en": "Will food technology like lab-grown meat change how we eat? What is your view?",
        "vocab": ["人造肉", "食品科技", "可持续", "接受", "未来"],
        "vocab_with_pinyin": [
            {"word": "人造肉", "pinyin": "rénzào ròu", "meaning": "lab-grown/artificial meat"},
            {"word": "可持续", "pinyin": "kě chíxù", "meaning": "sustainable"},
        ],
        "model_answer": "人造肉和其他食品科技正在改变我们对食物的认知。人造肉可以减少畜牧业对环境的破坏，也可以解决未来人口增长带来的粮食问题。但是，很多人可能还没办法接受吃人造食品，因为口感和真肉可能还有差距。我认为食品科技是未来的发展方向，我们应该以开放的态度去了解和尝试，因为这对人类和地球都有好处。",
        "followup_questions": ["你会吃人造肉吗？为什么？"],
        "scoring_hints": ["understands food tech concept", "environmental angle", "open-minded view"],
    },

    # ══════════════════════════════════════════════════════════
    # TOPIC: 科技 TECHNOLOGY  (Q71-Q80)
    # ══════════════════════════════════════════════════════════
    {
        "id": "Q71", "level": "P5", "topic": "科技",
        "emoji": "🤖",
        "image_url": "https://images.unsplash.com/photo-1485827404703-89b55fcc595e?w=600",
        "image_caption": "机器人",
        "question_zh": "图中是什么？人工智能和机器人会对未来的工作产生什么影响？",
        "question_en": "What is shown? How will AI and robots affect future jobs?",
        "vocab": ["人工智能", "机器人", "取代", "创新", "职业"],
        "vocab_with_pinyin": [
            {"word": "人工智能", "pinyin": "réngōng zhìnéng", "meaning": "artificial intelligence"},
            {"word": "取代", "pinyin": "qǔdài", "meaning": "to replace"},
        ],
        "model_answer": "图中是一个机器人，这是人工智能技术的体现。随着科技发展，机器人和人工智能将会取代一些重复性的工作，比如工厂流水线的工人或收银员。但与此同时，也会创造新的职业，如AI工程师和数据分析师。我认为未来的人才需要有创意思维和解决问题的能力，这些是机器人无法取代的。",
        "followup_questions": ["你认为哪些职业在未来最难被机器人取代？为什么？"],
        "scoring_hints": ["identifies AI/robot", "discusses job impact", "forward-looking view on skills"],
    },
    {
        "id": "Q72", "level": "P4", "topic": "科技",
        "emoji": "📱",
        "image_url": "https://images.unsplash.com/photo-1511707171634-5f897ff02aa9?w=600",
        "image_caption": "智能手机",
        "question_zh": "智能手机能帮我们做什么？你认为它对生活有什么影响？",
        "question_en": "What can smartphones help us do? How do they affect our lives?",
        "vocab": ["智能手机", "应用程序", "通讯", "便利", "依赖"],
        "vocab_with_pinyin": [
            {"word": "应用程序", "pinyin": "yìngyòng chéngsù", "meaning": "applications/apps"},
            {"word": "依赖", "pinyin": "yīlài", "meaning": "dependence/reliance"},
        ],
        "model_answer": "智能手机能帮我们做很多事情：用应用程序学习和查资料，与家人和朋友保持联系，导航找路，以及娱乐等等。智能手机让生活变得更便利，但也让一些人过于依赖它。我认为我们要善用手机，把它作为帮助我们的工具，而不是让它控制我们的生活。",
        "followup_questions": ["如果没有了手机，你的生活会有什么不同？"],
        "scoring_hints": ["lists smartphone uses", "discusses positive and negative impacts", "balanced view"],
    },
    {
        "id": "Q73", "level": "P6", "topic": "科技",
        "emoji": "🌐",
        "image_url": "https://images.unsplash.com/photo-1558494949-ef010cbdcc31?w=600",
        "image_caption": "网络安全",
        "question_zh": "上网时有什么安全风险？我们应该怎样保护自己的网络安全？",
        "question_en": "What are online safety risks? How can we protect our cybersecurity?",
        "vocab": ["网络安全", "骗局", "隐私", "密码", "谨慎"],
        "vocab_with_pinyin": [
            {"word": "网络安全", "pinyin": "wǎngluò ānquán", "meaning": "cybersecurity"},
            {"word": "隐私", "pinyin": "yǐnsī", "meaning": "privacy"},
        ],
        "model_answer": "上网有很多安全风险：网络骗局可能诱骗我们透露个人信息或金钱；网络霸凌可能对心理造成伤害；不良内容也可能对未成年人造成不良影响。为了保护网络安全，我们要使用强密码，不随意透露个人信息，对陌生人的信息保持警惕，遇到可疑情况要告诉父母或老师。",
        "followup_questions": ["如果你在网上遇到网络骗局，你应该怎么做？"],
        "scoring_hints": ["identifies online risks", "gives practical safety tips", "reporting unsafe situations"],
    },
    {
        "id": "Q74", "level": "P5", "topic": "科技",
        "emoji": "🚗",
        "image_url": "https://images.unsplash.com/photo-1549317661-bd32c8ce0db2?w=600",
        "image_caption": "自动驾驶汽车",
        "question_zh": "图中展示了什么未来科技？自动驾驶汽车对社会有什么影响？",
        "question_en": "What future technology is shown? How will self-driving cars affect society?",
        "vocab": ["自动驾驶", "安全", "效率", "交通", "革命"],
        "vocab_with_pinyin": [
            {"word": "自动驾驶", "pinyin": "zìdòng jiàshǐ", "meaning": "self-driving"},
            {"word": "革命", "pinyin": "gémìng", "meaning": "revolution"},
        ],
        "model_answer": "图中展示了自动驾驶汽车，这是未来交通科技的代表。自动驾驶汽车对社会有很多影响：它可能比人类驾驶更安全，减少因人为失误导致的交通事故；老人和残障人士也能更方便地出行；交通效率也可能因此提高。但同时，出租车司机等职业可能会受到影响。新加坡已经在测试自动驾驶巴士了。",
        "followup_questions": ["你认为自动驾驶汽车会完全取代人类司机吗？"],
        "scoring_hints": ["identifies self-driving car", "discusses impact on society", "local context"],
    },
    {
        "id": "Q75", "level": "P4", "topic": "科技",
        "emoji": "🎮",
        "image_url": "https://images.unsplash.com/photo-1493711662062-fa541adb3fc8?w=600",
        "image_caption": "电子游戏",
        "question_zh": "图中的孩子在做什么？玩电子游戏有好处吗？",
        "question_en": "What is the child doing? Are there benefits to playing video games?",
        "vocab": ["电子游戏", "反应", "团队", "沉迷", "节制"],
        "vocab_with_pinyin": [
            {"word": "沉迷", "pinyin": "chénmí", "meaning": "to be addicted to"},
            {"word": "反应", "pinyin": "fǎnyìng", "meaning": "reaction/response"},
        ],
        "model_answer": "图中的孩子正在打电子游戏。玩电子游戏有一些好处，比如可以锻炼反应能力，培养策略思维，多人游戏也能培养团队合作精神。但是，过度沉迷游戏会影响学习、睡眠和健康。我认为玩游戏要有节制，每天玩的时间不超过一个小时，学习和游戏都要有平衡。",
        "followup_questions": ["你最喜欢玩什么游戏？为什么喜欢它？"],
        "scoring_hints": ["discusses benefits", "addresses risks", "advocates moderation"],
    },
    {
        "id": "Q76", "level": "P6", "topic": "科技",
        "emoji": "🏥",
        "image_url": "https://images.unsplash.com/photo-1576671081837-49000212a370?w=600",
        "image_caption": "医疗科技",
        "question_zh": "科技怎样改变了现代医疗？举例说明。",
        "question_en": "How has technology changed modern medicine? Give examples.",
        "vocab": ["医疗科技", "诊断", "手术", "远程", "精准"],
        "vocab_with_pinyin": [
            {"word": "诊断", "pinyin": "zhěnduàn", "meaning": "diagnosis"},
            {"word": "精准", "pinyin": "jīngzhǔn", "meaning": "precise/accurate"},
        ],
        "model_answer": "科技极大地改变了现代医疗。例如，人工智能可以帮助医生更精准地诊断疾病，比如分析X光片；机器人手术系统让手术更精确，减少伤口；远程医疗让病人不必出门就能看医生；可穿戴设备能实时监测心率和血压。新加坡的医疗科技非常先进，是亚洲的医疗中心之一。",
        "followup_questions": ["你认为未来人工智能能完全取代医生吗？"],
        "scoring_hints": ["gives specific tech examples", "explains how they help", "Singapore medical hub"],
    },
    {
        "id": "Q77", "level": "P5", "topic": "科技",
        "emoji": "📚",
        "image_url": "https://images.unsplash.com/photo-1487058792275-0ad4aaf24ca7?w=600",
        "image_caption": "在线学习",
        "question_zh": "在线学习和传统课堂学习有什么不同？各有什么优缺点？",
        "question_en": "How is online learning different from traditional classroom learning? Pros and cons of each?",
        "vocab": ["在线学习", "灵活", "互动", "专注", "孤独"],
        "vocab_with_pinyin": [
            {"word": "灵活", "pinyin": "línghuó", "meaning": "flexible"},
            {"word": "互动", "pinyin": "hùdòng", "meaning": "interaction"},
        ],
        "model_answer": "在线学习和传统课堂各有优缺点。在线学习的好处是时间灵活，可以随时随地学习，资源丰富；缺点是缺乏与老师和同学的互动，容易分心。传统课堂的好处是有老师直接指导，同学之间可以互相帮助；缺点是时间固定，进度对所有人一样。我认为两者结合是最理想的学习方式。",
        "followup_questions": ["新冠疫情期间居家学习让你有什么体会？"],
        "scoring_hints": ["discusses both pros and cons", "balanced comparison", "COVID-19 relevance"],
    },
    {
        "id": "Q78", "level": "P4", "topic": "科技",
        "emoji": "🛸",
        "image_url": "https://images.unsplash.com/photo-1446776811953-b23d57bd21aa?w=600",
        "image_caption": "太空探索",
        "question_zh": "图中是什么？人类探索太空有什么意义？",
        "question_en": "What is shown? What is the significance of human space exploration?",
        "vocab": ["太空", "探索", "宇宙", "科学", "梦想"],
        "vocab_with_pinyin": [
            {"word": "探索", "pinyin": "tànsuǒ", "meaning": "exploration"},
            {"word": "宇宙", "pinyin": "yǔzhòu", "meaning": "universe"},
        ],
        "model_answer": "图中是太空火箭，象征着人类探索宇宙的梦想。人类探索太空有很大的意义：可以扩展我们对宇宙的认识，寻找地球以外的生命；太空探索也推动了很多科技的发展，这些科技后来被应用在我们的日常生活中；太空探索也激励了许多年轻人对科学产生兴趣。我希望将来能当宇航员，探索神秘的宇宙。",
        "followup_questions": ["你认为在太空探索上花费大量金钱是否值得？"],
        "scoring_hints": ["identifies rocket", "gives multiple reasons for space exploration", "aspirational element"],
    },
    {
        "id": "Q79", "level": "P6", "topic": "科技",
        "emoji": "🔋",
        "image_url": "https://images.unsplash.com/photo-1593941707882-a5bba14938c7?w=600",
        "image_caption": "电动汽车",
        "question_zh": "图中是什么车？电动汽车有什么好处和局限性？",
        "question_en": "What vehicle is shown? What are the benefits and limitations of electric cars?",
        "vocab": ["电动汽车", "充电", "续航", "环保", "基础设施"],
        "vocab_with_pinyin": [
            {"word": "电动汽车", "pinyin": "diàndòng qìchē", "meaning": "electric car"},
            {"word": "基础设施", "pinyin": "jīchǔ shèshī", "meaning": "infrastructure"},
        ],
        "model_answer": "图中是一辆正在充电的电动汽车。电动汽车的好处是不排放废气，对环境友好，行驶成本也比汽油车低。局限性方面，充一次电需要较长时间，充电设施还不够普及，价格也比普通汽车贵。新加坡政府正在推动发展充电基础设施，鼓励更多人使用电动汽车，以减少碳排放。",
        "followup_questions": ["新加坡推广电动汽车面临什么特别的挑战？"],
        "scoring_hints": ["identifies EV", "balanced pros and cons", "Singapore EV policy"],
    },
    {
        "id": "Q80", "level": "P5", "topic": "科技",
        "emoji": "📡",
        "image_url": "https://images.unsplash.com/photo-1508514177221-188b1cf16e9d?w=600",
        "image_caption": "社交媒体",
        "question_zh": "社交媒体对青少年有什么好处和坏处？",
        "question_en": "What are the benefits and harms of social media for teenagers?",
        "vocab": ["社交媒体", "信息", "假新闻", "沟通", "形象"],
        "vocab_with_pinyin": [
            {"word": "假新闻", "pinyin": "jiǎ xīnwén", "meaning": "fake news"},
            {"word": "形象", "pinyin": "xíngxiàng", "meaning": "image/appearance"},
        ],
        "model_answer": "社交媒体对青少年有好处也有坏处。好处方面，它能帮助我们与朋友保持联系，获取信息和学习资源，还能表达自己的想法和才华。坏处方面，社交媒体上的假新闻容易误导我们，网络霸凌也时有发生，过度关注他人的完美形象也会影响自信心。我们要有辨别能力，学会正确使用社交媒体。",
        "followup_questions": ["你认为社交媒体上的内容都是真实的吗？你怎么辨别真假信息？"],
        "scoring_hints": ["balanced benefits and harms", "gives specific examples", "critical thinking about media"],
    },

    # ══════════════════════════════════════════════════════════
    # TOPIC: 运动 SPORTS  (Q81-Q90)
    # ══════════════════════════════════════════════════════════
    {
        "id": "Q81", "level": "P4", "topic": "运动",
        "emoji": "⚽",
        "image_url": "https://images.unsplash.com/photo-1579952363873-27f3bade9f55?w=600",
        "image_caption": "踢足球",
        "question_zh": "图中的孩子在做什么运动？你喜欢什么运动？为什么？",
        "question_en": "What sport are the children playing? What sport do you like? Why?",
        "vocab": ["足球", "团队", "合作", "竞争", "锻炼"],
        "vocab_with_pinyin": [
            {"word": "合作", "pinyin": "hézuò", "meaning": "cooperation"},
            {"word": "竞争", "pinyin": "jìngzhēng", "meaning": "competition"},
        ],
        "model_answer": "图中的孩子们在踢足球，他们跑得很快，看起来非常投入。我最喜欢游泳，因为游泳能锻炼全身的肌肉，也对关节很友好。每周末，我都会去社区游泳池游泳，每次游完都感到精神爽快。运动不仅对身体好，还能帮助我减轻学习压力。",
        "followup_questions": ["你参加了什么学校体育队或课外活动？"],
        "scoring_hints": ["describes football", "shares own sport preference", "explains why"],
    },
    {
        "id": "Q82", "level": "P5", "topic": "运动",
        "emoji": "🏊",
        "image_url": "https://images.unsplash.com/photo-1530549387789-4c1017266635?w=600",
        "image_caption": "游泳比赛",
        "question_zh": "图中是什么比赛？参加体育竞赛对运动员有什么影响？",
        "question_en": "What competition is shown? How does participating in sports competitions affect athletes?",
        "vocab": ["比赛", "竞争", "心理", "压力", "胜负"],
        "vocab_with_pinyin": [
            {"word": "竞争", "pinyin": "jìngzhēng", "meaning": "competition"},
            {"word": "胜负", "pinyin": "shèngfù", "meaning": "win or lose"},
        ],
        "model_answer": "图中是游泳比赛，运动员们在奋力冲刺。参加体育竞赛对运动员有很大影响：一方面，比赛能激励运动员提高水平，培养不屈不挠的精神；另一方面，竞赛带来的压力也需要好好管理。我认为最重要的不是胜负，而是在比赛中挑战自己，发挥最佳水平，尽力而为。",
        "followup_questions": ["你参加过什么比赛？输了之后你是怎么面对的？"],
        "scoring_hints": ["describes swimming competition", "discusses competition effects", "sportsmanship message"],
    },
    {
        "id": "Q83", "level": "P4", "topic": "运动",
        "emoji": "🏸",
        "image_url": "https://images.unsplash.com/photo-1626224583764-f87db24ac4ea?w=600",
        "image_caption": "羽毛球",
        "question_zh": "图中是什么运动？你认为哪些运动最适合新加坡的气候？",
        "question_en": "What sport is shown? What sports are most suitable for Singapore's climate?",
        "vocab": ["羽毛球", "气候", "热带", "室内", "户外"],
        "vocab_with_pinyin": [
            {"word": "热带", "pinyin": "rèdài", "meaning": "tropical"},
            {"word": "室内", "pinyin": "shìnèi", "meaning": "indoor"},
        ],
        "model_answer": "图中是羽毛球运动，两名球员在激烈对打。新加坡是热带国家，天气炎热潮湿，所以很多人喜欢选择室内运动，如羽毛球、乒乓球和篮球。但如果在清晨或傍晚，气温没那么高，我们也可以在户外跑步、骑车或打球。我最喜欢在傍晚时到公园跑步，享受凉爽的微风。",
        "followup_questions": ["新加坡的气候对人们的运动习惯有什么影响？"],
        "scoring_hints": ["identifies badminton", "discusses climate and sports", "local examples"],
    },
    {
        "id": "Q84", "level": "P6", "topic": "运动",
        "emoji": "🏅",
        "image_url": "https://images.unsplash.com/photo-1461896836934-ffe607ba8211?w=600",
        "image_caption": "奥运会",
        "question_zh": "奥运会对新加坡的意义是什么？新加坡在体育方面有什么成就？",
        "question_en": "What does the Olympics mean for Singapore? What sporting achievements does Singapore have?",
        "vocab": ["奥运会", "成就", "骄傲", "体育精神", "代表"],
        "vocab_with_pinyin": [
            {"word": "成就", "pinyin": "chéngjiù", "meaning": "achievement"},
            {"word": "体育精神", "pinyin": "tǐyù jīngshén", "meaning": "sportsmanship"},
        ],
        "model_answer": "奥运会是全球最重要的体育盛事，对新加坡意义重大。2016年，新加坡游泳运动员约瑟林·史古林赢得了新加坡首枚奥运金牌，举国欢腾，让全体新加坡人感到骄傲。这个成就激励了许多新加坡年轻人追求体育梦想。我认为奥运会不只是关于金牌，更重要的是展示坚持不懈和体育精神。",
        "followup_questions": ["你希望新加坡在哪些体育项目上取得更好的成绩？为什么？"],
        "scoring_hints": ["mentions Joseph Schooling", "explains significance", "sportsmanship values"],
    },
    {
        "id": "Q85", "level": "P5", "topic": "运动",
        "emoji": "🧗",
        "image_url": "https://images.unsplash.com/photo-1522163182402-834f871fd851?w=600",
        "image_caption": "攀岩",
        "question_zh": "图中是什么运动？尝试新的极限运动有什么好处？",
        "question_en": "What sport is shown? What are the benefits of trying extreme sports?",
        "vocab": ["攀岩", "勇气", "挑战", "克服", "恐惧"],
        "vocab_with_pinyin": [
            {"word": "克服", "pinyin": "kèfú", "meaning": "to overcome"},
            {"word": "恐惧", "pinyin": "kǒngjù", "meaning": "fear"},
        ],
        "model_answer": "图中是攀岩运动，攀岩者正在努力攀爬岩壁，看起来非常考验体力和意志力。尝试新的极限运动能帮助我们克服恐惧，建立自信心；还能锻炼解决问题和快速决策的能力；更重要的是，克服困难的经历能让我们在日常生活和学习中更有毅力。我也想试试室内攀岩，挑战自己！",
        "followup_questions": ["你害怕尝试新事物吗？你是怎么克服恐惧的？"],
        "scoring_hints": ["identifies rock climbing", "discusses psychological benefits", "personal reflection on fear"],
    },
    {
        "id": "Q86", "level": "P4", "topic": "运动",
        "emoji": "🤸",
        "image_url": "https://images.unsplash.com/photo-1540497077202-7c8a3999166f?w=600",
        "image_caption": "体操",
        "question_zh": "图中是什么运动？这项运动需要什么特质？",
        "question_en": "What sport is shown? What qualities does this sport require?",
        "vocab": ["体操", "灵活", "毅力", "平衡", "训练"],
        "vocab_with_pinyin": [
            {"word": "灵活", "pinyin": "línghuó", "meaning": "flexible/agile"},
            {"word": "毅力", "pinyin": "yìlì", "meaning": "perseverance/willpower"},
        ],
        "model_answer": "图中是体操运动，运动员正在展示高难度的动作。体操需要多种特质：首先需要高度的灵活性和平衡感；其次需要强大的肌肉力量；最重要的是需要极大的毅力，因为学会一个新动作往往需要数百次的练习。体操运动员从小就开始训练，非常辛苦，令人敬佩。",
        "followup_questions": ["你认为运动员在儿童时期就开始专业训练是好事吗？"],
        "scoring_hints": ["identifies gymnastics", "lists required qualities", "admiration for athletes"],
    },
    {
        "id": "Q87", "level": "P6", "topic": "运动",
        "emoji": "🏋️",
        "image_url": "https://images.unsplash.com/photo-1534438327276-14e5300c3a48?w=600",
        "image_caption": "健身房",
        "question_zh": "图中是什么地方？运动对心理健康有什么好处？",
        "question_en": "What place is shown? How does exercise benefit mental health?",
        "vocab": ["健身房", "心理健康", "内啡肽", "压力", "自信"],
        "vocab_with_pinyin": [
            {"word": "内啡肽", "pinyin": "nèifēitài", "meaning": "endorphins"},
            {"word": "自信", "pinyin": "zìxìn", "meaning": "self-confidence"},
        ],
        "model_answer": "图中是健身房，有很多健身器材。运动对心理健康有很大好处：运动时大脑会分泌内啡肽，让人感到快乐和放松；规律运动能减轻焦虑和抑郁；还能提高自信心，因为坚持运动目标会给我们成就感。对于学业压力重的新加坡学生来说，运动是一个很好的减压方式。",
        "followup_questions": ["运动和休息对于学生来说，哪个更重要？"],
        "scoring_hints": ["identifies gym", "discusses mental health benefits", "relates to student stress"],
    },
    {
        "id": "Q88", "level": "P4", "topic": "运动",
        "emoji": "🤼",
        "image_url": "https://images.unsplash.com/photo-1544551763-46a013bb70d5?w=600",
        "image_caption": "团队运动",
        "question_zh": "图中是什么运动？团队运动和个人运动有什么不同？",
        "question_en": "What sport is shown? How do team sports differ from individual sports?",
        "vocab": ["团队运动", "个人", "责任", "配合", "沟通"],
        "vocab_with_pinyin": [
            {"word": "配合", "pinyin": "pèihé", "meaning": "to coordinate"},
            {"word": "沟通", "pinyin": "gōutōng", "meaning": "communication"},
        ],
        "model_answer": "图中是团队运动，球员们正在互相配合。团队运动和个人运动有很大的不同：团队运动需要队员之间良好的沟通和配合，如果一个人表现不好，整队都会受影响；个人运动则只需要专注于自己的表现。团队运动能培养我们的团队精神和责任感，这在生活中非常重要。",
        "followup_questions": ["你更喜欢团队运动还是个人运动？为什么？"],
        "scoring_hints": ["describes team sport", "compares team vs individual", "values of teamwork"],
    },
    {
        "id": "Q89", "level": "P5", "topic": "运动",
        "emoji": "🎾",
        "image_url": "https://images.unsplash.com/photo-1551958219-acbc595d3be5?w=600",
        "image_caption": "网球",
        "question_zh": "图中是什么运动？学习一项新运动有什么挑战？",
        "question_en": "What sport is shown? What challenges come with learning a new sport?",
        "vocab": ["网球", "技巧", "耐心", "失败", "进步"],
        "vocab_with_pinyin": [
            {"word": "耐心", "pinyin": "nàixīn", "meaning": "patience"},
            {"word": "进步", "pinyin": "jìnbù", "meaning": "progress/improvement"},
        ],
        "model_answer": "图中是网球运动，球员正在挥拍击球。学习一项新运动有很多挑战：开始的时候往往很难掌握技巧，容易感到气馁；还需要花很多时间练习；身体也需要时间适应新的动作。但是，克服这些挑战之后，当技术有所进步，那种成就感是无可比拟的。我学游泳的时候也经历过这样的过程，坚持下来就成功了。",
        "followup_questions": ["当你学习一样新技能遇到困难时，你是怎么坚持下去的？"],
        "scoring_hints": ["identifies tennis", "lists challenges", "emphasises perseverance"],
    },
    {
        "id": "Q90", "level": "P6", "topic": "运动",
        "emoji": "🏟️",
        "image_url": "https://images.unsplash.com/photo-1577223625816-7546f13df25d?w=600",
        "image_caption": "新加坡体育场",
        "question_zh": "大型体育设施对新加坡有什么好处？承办大型体育赛事有什么意义？",
        "question_en": "What are the benefits of large sports facilities to Singapore? What is the significance of hosting major events?",
        "vocab": ["体育场", "基础设施", "旅游", "经济", "形象"],
        "vocab_with_pinyin": [
            {"word": "基础设施", "pinyin": "jīchǔ shèshī", "meaning": "infrastructure"},
            {"word": "形象", "pinyin": "xíngxiàng", "meaning": "image/reputation"},
        ],
        "model_answer": "新加坡体育场是世界上最大的可开合式运动场之一，是新加坡重要的体育基础设施。承办大型体育赛事对新加坡好处很多：能吸引国际游客，促进旅游业和经济发展；提升新加坡的国际形象；也能激励本地年轻人投入体育运动。新加坡曾承办过多项重大赛事，充分展示了我们的组织能力。",
        "followup_questions": ["你认为新加坡应该继续在大型体育设施上投资吗？"],
        "scoring_hints": ["mentions Singapore Sports Hub", "multiple benefits", "economic and cultural angle"],
    },

    # ══════════════════════════════════════════════════════════
    # TOPIC: 动物 ANIMALS  (Q91-Q100)
    # ══════════════════════════════════════════════════════════
    {
        "id": "Q91", "level": "P4", "topic": "动物",
        "emoji": "🐯",
        "image_url": "https://images.unsplash.com/photo-1561731216-c3a4d99437d5?w=600",
        "image_caption": "动物园里的老虎",
        "question_zh": "图中是什么动物？你去过动物园吗？你有什么感受？",
        "question_en": "What animal is shown? Have you been to the zoo? How did you feel?",
        "vocab": ["老虎", "动物园", "野生", "保护", "濒危"],
        "vocab_with_pinyin": [
            {"word": "老虎", "pinyin": "lǎohǔ", "meaning": "tiger"},
            {"word": "濒危", "pinyin": "bīnwēi", "meaning": "endangered"},
        ],
        "model_answer": "图中是一只威武的老虎，它是世界上最美丽也是最危险的动物之一。我去过新加坡野生动物园，看到各种各样的动物，非常兴奋。老虎是濒临绝种的动物，看到它让我想到人类保护野生动物的责任。动物园不只是娱乐的地方，也是保育濒危动物的重要机构。",
        "followup_questions": ["你认为动物应该关在动物园里吗？为什么？"],
        "scoring_hints": ["identifies tiger", "shares zoo experience", "mentions conservation"],
    },
    {
        "id": "Q92", "level": "P4", "topic": "动物",
        "emoji": "🐕",
        "image_url": "https://images.unsplash.com/photo-1587300003388-59208cc962cb?w=600",
        "image_caption": "宠物狗",
        "question_zh": "图中的动物是什么？你有宠物吗？养宠物有什么好处和责任？",
        "question_en": "What animal is shown? Do you have a pet? What are the benefits and responsibilities of keeping one?",
        "vocab": ["宠物", "责任", "陪伴", "照顾", "喂食"],
        "vocab_with_pinyin": [
            {"word": "陪伴", "pinyin": "péibàn", "meaning": "company/companionship"},
            {"word": "责任", "pinyin": "zérèn", "meaning": "responsibility"},
        ],
        "model_answer": "图中是一只可爱的狗狗，看起来非常活泼。我家里养了一只叫豆豆的小狗，它是我最好的朋友。养宠物有很多好处：宠物能给我们带来陪伴和快乐，还能培养我们的责任感。但养宠物也有很大的责任，我们必须每天喂食、带它运动，还要定期带它看兽医。养宠物是一辈子的承诺，不能随便放弃。",
        "followup_questions": ["如果有人不负责任地遗弃宠物，你认为应该怎么处理？"],
        "scoring_hints": ["describes pet", "lists benefits", "emphasises responsibility"],
    },
    {
        "id": "Q93", "level": "P5", "topic": "动物",
        "emoji": "🦋",
        "image_url": "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=600",
        "image_caption": "蝴蝶",
        "question_zh": "图中是什么昆虫？昆虫在生态系统中有什么重要作用？",
        "question_en": "What insect is shown? What important role do insects play in the ecosystem?",
        "vocab": ["蝴蝶", "授粉", "生态", "昆虫", "食物链"],
        "vocab_with_pinyin": [
            {"word": "授粉", "pinyin": "shòufěn", "meaning": "pollination"},
            {"word": "食物链", "pinyin": "shíwùliàn", "meaning": "food chain"},
        ],
        "model_answer": "图中是一只美丽的蝴蝶，它正停在花朵上。昆虫在生态系统中扮演着非常重要的角色：蝴蝶和蜜蜂是重要的传粉者，帮助植物繁殖，没有它们，很多植物就无法结果；昆虫也是食物链的重要一环，是很多鸟类和青蛙的食物。保护昆虫就是保护整个生态系统。",
        "followup_questions": ["如果蜜蜂灭绝了，对人类会有什么影响？"],
        "scoring_hints": ["identifies butterfly", "explains pollination role", "ecosystem importance"],
    },
    {
        "id": "Q94", "level": "P6", "topic": "动物",
        "emoji": "🐬",
        "image_url": "https://images.unsplash.com/photo-1568430462989-44163eb1752f?w=600",
        "image_caption": "海豚",
        "question_zh": "海豚是一种非常聪明的动物。你认为人类应该把海豚圈养在水族馆里供人观赏吗？",
        "question_en": "Dolphins are very intelligent. Should humans keep them in aquariums for entertainment?",
        "vocab": ["海豚", "圈养", "自然", "娱乐", "福利"],
        "vocab_with_pinyin": [
            {"word": "圈养", "pinyin": "quānyǎng", "meaning": "captivity"},
            {"word": "福利", "pinyin": "fúlì", "meaning": "welfare"},
        ],
        "model_answer": "这是一个很值得思考的问题。一方面，水族馆让更多人有机会近距离了解海豚，提高了公众对海洋动物的关注；另一方面，海豚是高智商的动物，圈养可能会影响它们的心理健康。我认为，我们应该优先考虑动物的福利，建设更大的自然环境供海豚生活，而不是把它们关在小水池里表演。",
        "followup_questions": ["你认为动物园和水族馆对野生动物保护有没有贡献？"],
        "scoring_hints": ["discusses both sides", "animal welfare perspective", "gives personal view"],
    },
    {
        "id": "Q95", "level": "P4", "topic": "动物",
        "emoji": "🐠",
        "image_url": "https://images.unsplash.com/photo-1535591273668-578e31182c4f?w=600",
        "image_caption": "热带鱼",
        "question_zh": "图中是什么鱼？你知道新加坡河流或海洋里有哪些生物吗？",
        "question_en": "What fish are shown? What wildlife lives in Singapore's rivers or seas?",
        "vocab": ["热带鱼", "海洋生物", "珊瑚", "河流", "生物多样性"],
        "vocab_with_pinyin": [
            {"word": "生物多样性", "pinyin": "shēngwù duōyàngxìng", "meaning": "biodiversity"},
        ],
        "model_answer": "图中是五颜六色的热带鱼，非常漂亮。新加坡虽然是一个小岛国，但拥有丰富的海洋和淡水生物多样性。新加坡的海域有珊瑚礁，里面住着各种热带鱼和海洋生物；新加坡河经过治理后，也恢复了一些淡水鱼类。我曾经去过圣淘沙水族馆，看到了很多神奇的海洋生物。",
        "followup_questions": ["新加坡的水域曾经受到严重污染，现在有所改善。你知道是怎么做到的吗？"],
        "scoring_hints": ["identifies tropical fish", "mentions Singapore marine life", "awareness of local environment"],
    },
    {
        "id": "Q96", "level": "P5", "topic": "动物",
        "emoji": "🐘",
        "image_url": "https://images.unsplash.com/photo-1557050543-4d5f4e07ef46?w=600",
        "image_caption": "大象家庭",
        "question_zh": "图中的大象在做什么？大象是一种有情感的动物，我们应该怎样对待它们？",
        "question_en": "What are the elephants doing? Elephants are emotional animals. How should we treat them?",
        "vocab": ["大象", "情感", "家庭", "尊重", "象牙"],
        "vocab_with_pinyin": [
            {"word": "象牙", "pinyin": "xiàngyá", "meaning": "ivory"},
            {"word": "尊重", "pinyin": "zūnzhòng", "meaning": "to respect"},
        ],
        "model_answer": "图中的大象家庭在一起玩耍，妈妈和小象紧靠在一起，非常温馨。大象是一种高度智慧和有情感的动物，它们有家庭观念，会互相照顾，甚至会为死去的同伴悲哀。我认为我们应该尊重大象，绝对不能购买象牙制品，因为这会助长偷猎行为，导致更多大象被杀害。",
        "followup_questions": ["你认为人类对动物是否有道义上的责任？为什么？"],
        "scoring_hints": ["describes elephants", "acknowledges emotional intelligence", "anti-poaching stance"],
    },
    {
        "id": "Q97", "level": "P4", "topic": "动物",
        "emoji": "🦁",
        "image_url": "https://images.unsplash.com/photo-1546182990-dffeafbe841d?w=600",
        "image_caption": "狮子",
        "question_zh": "图中是什么动物？新加坡的英文名字Singapore和狮子有什么关系？",
        "question_en": "What animal is shown? What is the connection between Singapore's name and the lion?",
        "vocab": ["狮子", "传说", "勇敢", "力量", "象征"],
        "vocab_with_pinyin": [
            {"word": "传说", "pinyin": "chuánshuō", "meaning": "legend"},
            {"word": "象征", "pinyin": "xiàngzhēng", "meaning": "symbol"},
        ],
        "model_answer": "图中是一头威武的狮子，在狮子王国中享有尊贵的地位。新加坡的英文名称Singapore来自古马来语'Singa Pura'，意思是'狮子城'。根据传说，马来王子圣尼罗乌达玛来到这个岛上，看到一只动物，以为是狮子，于是把这个地方命名为狮子城。狮子也成为了新加坡的象征，鱼尾狮就代表着狮子城。",
        "followup_questions": ["新加坡有哪些地标或标志体现了狮子的形象？"],
        "scoring_hints": ["identifies lion", "explains Singapore etymology", "Merlion connection"],
    },
    {
        "id": "Q98", "level": "P6", "topic": "动物",
        "emoji": "🦜",
        "image_url": "https://images.unsplash.com/photo-1552728089-57bdde30beb3?w=600",
        "image_caption": "鹦鹉",
        "question_zh": "图中的动物是什么？人类能教动物说话或做复杂的事情，这说明了什么？",
        "question_en": "What animal is shown? What does it mean that humans can teach animals to speak or do complex things?",
        "vocab": ["鹦鹉", "智慧", "模仿", "动物行为", "进化"],
        "vocab_with_pinyin": [
            {"word": "模仿", "pinyin": "mófǎng", "meaning": "to imitate"},
            {"word": "进化", "pinyin": "jìnhuà", "meaning": "evolution"},
        ],
        "model_answer": "图中是一只色彩鲜艳的鹦鹉，它是一种极具智慧的鸟类。人类能教鹦鹉说话，能教猩猩和海豚做复杂的任务，这说明动物的智慧比我们想象的更高。这也提醒我们，人类和动物之间的差异可能没有那么大，我们应该更尊重和善待动物。科学研究也证明，很多动物都有情感和社交关系。",
        "followup_questions": ["如果动物和人类一样聪明，我们的道德观念会有什么改变？"],
        "scoring_hints": ["identifies parrot", "discusses animal intelligence", "ethical implications"],
    },
    {
        "id": "Q99", "level": "P5", "topic": "动物",
        "emoji": "🐝",
        "image_url": "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=600",
        "image_caption": "蜜蜂授粉",
        "question_zh": "蜜蜂对人类有什么重要性？如果蜜蜂消失了，会怎样？",
        "question_en": "Why are bees important to humans? What would happen if bees disappeared?",
        "vocab": ["蜜蜂", "授粉", "粮食", "灭绝", "依存"],
        "vocab_with_pinyin": [
            {"word": "相互依存", "pinyin": "xiānghù yīcún", "meaning": "interdependence"},
        ],
        "model_answer": "蜜蜂对人类非常重要，主要因为它们是重要的传粉者。据科学家估计，全球约三分之一的食物生产依赖蜜蜂传粉。如果蜜蜂消失了，很多农作物将无法繁殖，粮食危机将会出现，生态系统也会受到严重破坏。这说明人类和自然界是相互依存的，保护蜜蜂就是保护人类自己的未来。",
        "followup_questions": ["你认为我们应该采取哪些措施来保护蜜蜂？"],
        "scoring_hints": ["explains bee importance", "describes consequences", "ecological thinking"],
    },
    {
        "id": "Q100", "level": "P6", "topic": "动物",
        "emoji": "🐢",
        "image_url": "https://images.unsplash.com/photo-1559827291-72ee739d0d9a?w=600",
        "image_caption": "海龟",
        "question_zh": "图中是什么动物？海龟面临哪些威胁？我们能做什么来帮助它们？",
        "question_en": "What animal is shown? What threats do sea turtles face? How can we help?",
        "vocab": ["海龟", "威胁", "塑料", "渔网", "保育"],
        "vocab_with_pinyin": [
            {"word": "保育", "pinyin": "bǎoyù", "meaning": "conservation"},
            {"word": "渔网", "pinyin": "yúwǎng", "meaning": "fishing net"},
        ],
        "model_answer": "图中是一只在海中游泳的海龟，看起来非常优雅。海龟面临很多威胁：塑料垃圾污染了海洋，海龟常常误食塑料袋；渔网也会意外捕捉海龟；全球暖化导致海水温度升高，影响海龟蛋的孵化。我们能做的有很多：减少使用一次性塑料，支持海洋保育组织，以及在旅游时不打扰海龟的栖息地。",
        "followup_questions": ["你认为最重要的一件可以立即做到的环保行动是什么？"],
        "scoring_hints": ["identifies sea turtle", "multiple threats", "practical personal actions"],
    },
]
